# Creates an immutable candidate with a temporary Git index.  The real index is
# touched only after a guarded ref advance, and then only for authorized paths.
[CmdletBinding()]
param(
	[Parameter(Mandatory)][ValidateSet('session-landing', 'primary-commit')][string] $Route,
	[Parameter(Mandatory)][string] $CurrentWorktree,
	[Parameter(Mandatory)][string] $PrimaryWorktree,
	[Parameter(Mandatory)][string] $CurrentBranch,
	[Parameter(Mandatory)][string] $PrimaryBranch,
	[Parameter(Mandatory)][string] $Baseline,
	[Parameter(Mandatory)][string] $ExpectedCurrentTip,
	[Parameter(Mandatory)][string] $ExpectedPrimaryTip,
	[Parameter(Mandatory)][string[]] $OwnedPaths,
	[Parameter(Mandatory)][string] $CommitMessageFile,
	[string] $VerifiedCandidateCommit,
	[string] $VerifiedCandidateTree,
	[switch] $AdvancePrimary,
	[ValidateSet('none', 'tree-mismatch', 'expected-tip-mismatch', 'postcondition', 'post-index-mutation')][string] $FixtureFailure = 'none'
)
$ErrorActionPreference = 'Stop'; Set-StrictMode -Version Latest
$result = [ordered]@{ schemaVersion='broken-engine-finalize-candidate/v2';status='error';code='internal.error';message='Candidate transaction did not complete.';route=$Route;baseline=$Baseline;tips=[ordered]@{current=$null;primary=$null;expectedCurrent=$ExpectedCurrentTip;expectedPrimary=$ExpectedPrimaryTip};candidate=[ordered]@{commit=$null;tree=$null;parent=$null;singleParent=$false;reconciled=$false};ownedPaths=@();state=[ordered]@{before=$null;after=$null;unrelatedPreserved=$false;realIndexUntouched=$null};primaryAdvance=[ordered]@{attempted=$false;advanced=$false;rollback='not-required'} }
function Complete([int]$Exit,[string]$Status,[string]$Code,[string]$Message){$result.status=$Status;$result.code=$Code;$result.message=$Message;Write-Output ($result|ConvertTo-Json -Depth 16 -Compress);exit $Exit}
function Stop-Candidate([int]$Exit,[string]$Code,[string]$Message){$e=[InvalidOperationException]::new($Message);$e.Data['exit']=$Exit;$e.Data['code']=$Code;throw $e}
function Invoke-Native([string]$Root,[string]$Exe,[string[]]$Arguments,[hashtable]$Environment=@{}){$p=[Diagnostics.ProcessStartInfo]::new();$p.FileName=$Exe;$p.WorkingDirectory=$Root;$p.UseShellExecute=$false;$p.CreateNoWindow=$true;$p.RedirectStandardOutput=$true;$p.RedirectStandardError=$true;foreach($a in $Arguments){[void]$p.ArgumentList.Add($a)};foreach($k in $Environment.Keys){$p.Environment[$k]=$Environment[$k]};$x=[Diagnostics.Process]::new();$x.StartInfo=$p;if(-not$x.Start()){throw "Could not start '$Exe'."};$o=$x.StandardOutput.ReadToEndAsync();$e=$x.StandardError.ReadToEndAsync();$x.WaitForExit();$r=[pscustomobject]@{ExitCode=$x.ExitCode;Stdout=$o.GetAwaiter().GetResult();Stderr=$e.GetAwaiter().GetResult()};$x.Dispose();return $r}
# The stdin parameter must not be named $Input: PowerShell's automatic $input enumerator overwrites a same-named parameter, silently sending empty stdin.
function Invoke-NativeInput([string]$Root,[string]$Exe,[string[]]$Arguments,[string]$InputText){$p=[Diagnostics.ProcessStartInfo]::new();$p.FileName=$Exe;$p.WorkingDirectory=$Root;$p.UseShellExecute=$false;$p.CreateNoWindow=$true;$p.RedirectStandardOutput=$true;$p.RedirectStandardError=$true;$p.RedirectStandardInput=$true;foreach($a in $Arguments){[void]$p.ArgumentList.Add($a)};$x=[Diagnostics.Process]::new();$x.StartInfo=$p;if(-not$x.Start()){throw "Could not start '$Exe'."};$x.StandardInput.Write($InputText);$x.StandardInput.Close();$o=$x.StandardOutput.ReadToEndAsync();$e=$x.StandardError.ReadToEndAsync();$x.WaitForExit();$r=[pscustomobject]@{ExitCode=$x.ExitCode;Stdout=$o.GetAwaiter().GetResult();Stderr=$e.GetAwaiter().GetResult()};$x.Dispose();return $r}
function Invoke-Git([string]$Root,[string[]]$Arguments,[hashtable]$Environment=@{}){$r=Invoke-Native $Root 'git.exe' (@('-C',$Root)+$Arguments) $Environment;if($r.ExitCode-ne 0){throw "git $($Arguments -join ' ') failed: $($r.Stderr.Trim())"};return $r.Stdout}
function Test-Git([string]$Root,[string[]]$Arguments){return (Invoke-Native $Root 'git.exe' (@('-C',$Root)+$Arguments)).ExitCode-eq 0}
function Normalize-Path([string]$Path){$p=$Path.Replace('\','/');if([string]::IsNullOrWhiteSpace($p)-or[IO.Path]::IsPathRooted($p)-or$p -eq '.'-or$p -eq '..'-or$p.StartsWith('../')-or$p.Contains('/../')-or$p.EndsWith('/..')-or$p.StartsWith('./')-or$p.Contains('/./')-or$p.EndsWith('/.')-or$p.Contains('//')-or$p.Contains([char]0)-or$p -match '[*?:]'){Stop-Candidate 1 'input.path-invalid' "Invalid literal repository-relative path '$Path'."};return $p}
function Get-LiteralPathspec([string]$Path){return ":(literal)$Path"}
function Get-Status([string]$Root){return Invoke-Git $Root @('status','--porcelain=v1','-z','--untracked-files=all')}
function Get-StatusRecords([string]$Status){$records=[Collections.Generic.List[object]]::new();$t=@($Status-split[char]0);$i=0;while($i-lt$t.Count){$r=$t[$i++];if([string]::IsNullOrEmpty($r)){continue};if($r.Length-lt 4){throw "Malformed git status record '$r'."};$xy=$r.Substring(0,2);$path=Normalize-Path $r.Substring(3);$other=$null;if($xy -match 'R|C'){if($i-ge$t.Count){throw 'Rename status record is truncated.'};$other=Normalize-Path $t[$i++]};$records.Add([pscustomobject]@{XY=$xy;Path=$path;Other=$other})};return @($records)}
function Filter-Status([string]$Status,[string[]]$Owned,[bool]$WantOwned){$out=[Text.StringBuilder]::new();foreach($r in Get-StatusRecords $Status){$hit=($Owned-ccontains$r.Path)-or($null-ne$r.Other-and$Owned-ccontains$r.Other);if($hit-eq$WantOwned){[void]$out.Append($r.XY).Append('|').Append($r.Path).Append('|').Append($r.Other).Append("`0")}};return $out.ToString()}
function Assert-OwnedNotMixed([string]$Status,[string[]]$Owned){foreach($r in Get-StatusRecords $Status){$hit=($Owned-ccontains$r.Path)-or($null-ne$r.Other-and$Owned-ccontains$r.Other);if($hit-and$r.XY[0]-ne ' '-and$r.XY[0]-ne '?' -and$r.XY[1]-ne ' '-and$r.XY[1]-ne '?'){Stop-Candidate 2 'git.owned-path-mixed-state' "Authorized path '$($r.Path)' has mixed index and worktree state."}}}
function Get-Tree([string]$Root,[string]$Commit){return (Invoke-Git $Root @('rev-parse',"$Commit^{tree}")).Trim()}
function Assert-ExactCommit([string]$Root,[string]$Commit,[string]$Name){if($Commit-cnotmatch'^[0-9a-f]{40}$'-or(Invoke-Git $Root @('rev-parse','--verify',"$Commit^{commit}")).Trim()-cne$Commit){Stop-Candidate 1 'input.commit-invalid' "$Name is not an exact commit identity."}}
function Assert-Candidate([string]$Root,[string]$Commit,[string]$Tree,[string]$Parent){Assert-ExactCommit $Root $Commit 'VerifiedCandidateCommit';if($Tree-cnotmatch'^[0-9a-f]{40}$'-or(Get-Tree $Root $Commit)-cne$Tree){Stop-Candidate 2 'candidate.tree-mismatch' 'Verified candidate tree is not the candidate commit tree.'};$parents=@((Invoke-Git $Root @('show','-s','--format=%P',$Commit)).Trim().Split(' ',[StringSplitOptions]::RemoveEmptyEntries));if($parents.Count-ne 1-or$parents[0]-cne$Parent){Stop-Candidate 2 'candidate.parent-invalid' 'Verified candidate does not have the required sole parent.'}}
function Get-ExactTreeEntry([string]$Root,[string]$Tree,[string]$Path){$lines=@((Invoke-Git $Root @('ls-tree',$Tree,'--',(Get-LiteralPathspec $Path))).Trim().Split("`n",[StringSplitOptions]::RemoveEmptyEntries));if($lines.Count-eq 0){return $null};if($lines.Count-ne 1){Stop-Candidate 2 'input.path-not-single-entry' "Authorized path '$Path' resolves to multiple Git entries."};$m=[regex]::Match($lines[0],"^(?<mode>\d{6})\s+\w+\s+(?<oid>[0-9a-f]{40})\t(?<path>.+)$");if(-not$m.Success-or$m.Groups['path'].Value-cne$Path){Stop-Candidate 2 'input.path-not-single-entry' "Authorized path '$Path' is not one literal Git entry."};return [pscustomobject]@{Mode=$m.Groups['mode'].Value;Oid=$m.Groups['oid'].Value;Path=$Path}}
function Assert-LiteralPathEntry([string]$Root,[string]$Base,[string]$Path){$entry=Get-ExactTreeEntry $Root $Base $Path;$disk=Join-Path $Root ($Path.Replace('/','\'));if(Test-Path -LiteralPath $disk -PathType Container){if($null-eq$entry-or$entry.Mode-cne'160000'){Stop-Candidate 1 'input.path-directory' "Authorized path '$Path' is a directory, not one Git entry."}}elseif($null-eq$entry-and-not(Test-Path -LiteralPath $disk -PathType Leaf)){Stop-Candidate 1 'input.path-not-single-entry' "Authorized path '$Path' is neither an existing file nor a tracked deletion."};return $entry}
function Assert-LiteralPathEntries([string]$Root,[string]$Base,[string[]]$Paths){foreach($path in $Paths){[void](Assert-LiteralPathEntry $Root $Base $path)}}
function Set-IndexPathFromTree([string]$Root,[string]$Tree,[string]$Path){$entry=Get-ExactTreeEntry $Root $Tree $Path;if($null-eq$entry){Invoke-Git $Root @('update-index','--force-remove','--',$Path)|Out-Null;return};Invoke-Git $Root @('update-index','--add','--cacheinfo',"$($entry.Mode),$($entry.Oid),$Path")|Out-Null}
function Get-IndexPathSnapshot([string]$Root,[string[]]$Paths){$snapshot=[ordered]@{};foreach($path in $Paths){$records=[Collections.Generic.List[object]]::new();foreach($line in @((Invoke-Git $Root @('ls-files','--stage','-z','--',(Get-LiteralPathspec $path)))-split[char]0)){if([string]::IsNullOrEmpty($line)){continue};$m=[regex]::Match($line,"^(?<mode>\d{6})\s+(?<oid>[0-9a-f]{40})\s+(?<stage>[0-3])\t(?<path>.+)$");if(-not$m.Success-or$m.Groups['path'].Value-cne$path){throw "Malformed index entry for '$path'."};$records.Add([pscustomobject]@{Mode=$m.Groups['mode'].Value;Oid=$m.Groups['oid'].Value;Stage=$m.Groups['stage'].Value;Path=$path})};$snapshot[$path]=@($records)};return $snapshot}
function Restore-IndexPathSnapshot([string]$Root,$Snapshot){foreach($path in $Snapshot.Keys){Invoke-Git $Root @('update-index','--force-remove','--',$path)|Out-Null;$entries=@($Snapshot[$path]);if($entries.Count-eq 0){continue};$input=(($entries|ForEach-Object{"$($_.Mode) $($_.Oid) $($_.Stage)`t$($_.Path)"})-join"`n")+"`n";$r=Invoke-NativeInput $Root 'git.exe' (@('-C',$Root,'update-index','--add','--index-info')) $input;if($r.ExitCode-ne 0){throw "Could not restore index entry '$path': $($r.Stderr.Trim())"}}}
function Test-IndexPathSnapshot([string]$Root,$Snapshot){$actual=Get-IndexPathSnapshot $Root @($Snapshot.Keys);foreach($path in $Snapshot.Keys){$expectedText=(@($Snapshot[$path])|ForEach-Object{"$($_.Mode)|$($_.Oid)|$($_.Stage)|$($_.Path)"})-join"`n";$actualText=(@($actual[$path])|ForEach-Object{"$($_.Mode)|$($_.Oid)|$($_.Stage)|$($_.Path)"})-join"`n";if($expectedText-cne$actualText){return $false}};return $true}
function Assert-RouteIdentity([string]$Current,[string]$Primary){$ct=(Invoke-Git $Current @('rev-parse','--show-toplevel')).Trim();$pt=(Invoke-Git $Primary @('rev-parse','--show-toplevel')).Trim();if(-not([IO.Path]::GetFullPath($ct).TrimEnd('\','/').Equals($Current,[StringComparison]::OrdinalIgnoreCase))-or-not([IO.Path]::GetFullPath($pt).TrimEnd('\','/').Equals($Primary,[StringComparison]::OrdinalIgnoreCase))){Stop-Candidate 1 'identity.not-root' 'Current and primary worktrees must be Git roots.'};$cc=(Invoke-Git $Current @('rev-parse','--path-format=absolute','--git-common-dir')).Trim();$pc=(Invoke-Git $Primary @('rev-parse','--path-format=absolute','--git-common-dir')).Trim();if(-not$cc.Equals($pc,[StringComparison]::OrdinalIgnoreCase)){Stop-Candidate 1 'identity.repository-mismatch' 'Current and primary worktrees must share one common Git directory.'};if((Invoke-Git $Current @('branch','--show-current')).Trim()-cne$CurrentBranch-or(Invoke-Git $Primary @('branch','--show-current')).Trim()-cne$PrimaryBranch){Stop-Candidate 2 'identity.branch-mismatch' 'Checked-out branches do not match the requested route.'}}
try {
	if(-not(Test-Path -LiteralPath $CommitMessageFile -PathType Leaf)){Stop-Candidate 1 'input.message-missing' 'CommitMessageFile must be an existing ordinary file.'};foreach($h in @($Baseline,$ExpectedCurrentTip,$ExpectedPrimaryTip)){if($h-cnotmatch'^[0-9a-f]{40}$'){Stop-Candidate 1 'input.commit-invalid' 'Baseline and expected tips must be lowercase 40-character object IDs.'}}
	if($AdvancePrimary-and([string]::IsNullOrWhiteSpace($VerifiedCandidateCommit)-or[string]::IsNullOrWhiteSpace($VerifiedCandidateTree))){Stop-Candidate 1 'input.candidate-missing' 'Exact verified candidate commit and tree are mandatory for primary advance.'}
	# `pwsh -File` hands every argument over as one literal string, so several owned paths can only travel as one comma-separated token.
	$declared=@(@($OwnedPaths)|ForEach-Object{$_ -split ','}|ForEach-Object{Normalize-Path $_}|Sort-Object -Unique);$result.ownedPaths=$declared;$current=[IO.Path]::GetFullPath($CurrentWorktree).TrimEnd('\','/');$primary=[IO.Path]::GetFullPath($PrimaryWorktree).TrimEnd('\','/');Assert-RouteIdentity $current $primary;$head=(Invoke-Git $current @('rev-parse','HEAD')).Trim();$primaryHead=(Invoke-Git $primary @('rev-parse','HEAD')).Trim();$result.tips.current=$head;$result.tips.primary=$primaryHead
	if($Route-eq'session-landing'){
		if($head-cne$ExpectedCurrentTip-or$primaryHead-cne$ExpectedPrimaryTip){Stop-Candidate 2 'git.tip-changed' 'Session or primary tip changed before candidate creation.'};$owned=$declared;if($owned.Count-eq 0){Stop-Candidate 1 'input.owned-paths-empty' 'At least one caller-owned path is required.'};Assert-LiteralPathEntries $current $ExpectedCurrentTip $owned
		$before=Get-Status $current;$result.state.before=$before;Assert-OwnedNotMixed $before $owned;$unrelatedBefore=Filter-Status $before $owned $false;$ownedBefore=Filter-Status $before $owned $true;$indexSnapshot=Get-IndexPathSnapshot $current $owned;$tmp=Join-Path([IO.Path]::GetTempPath())('BrokenEngineFinalizeCandidate-'+[guid]::NewGuid().ToString('N')+'.index');try{$env=@{GIT_INDEX_FILE=$tmp};Invoke-Git $current @('read-tree',$ExpectedCurrentTip) $env|Out-Null;Invoke-Git -Root $current -Arguments (@('add','-A','--')+@($owned|ForEach-Object{Get-LiteralPathspec $_})) -Environment $env|Out-Null;$tree=(Invoke-Git $current @('write-tree') $env).Trim();$candidate=(Invoke-Git $current @('commit-tree',$tree,'-p',$ExpectedCurrentTip,'-F',$CommitMessageFile) $env).Trim();$cas=Invoke-Native $current 'git.exe' @('-C',$current,'update-ref',"refs/heads/$CurrentBranch",$candidate,$ExpectedCurrentTip);if($cas.ExitCode-ne 0){Stop-Candidate 2 'git.compare-and-swap-failed' 'Session branch changed before candidate creation.'};try{$mutations=0;foreach($path in $owned){Set-IndexPathFromTree $current $tree $path;$mutations++;if($FixtureFailure-eq'post-index-mutation'-and$mutations-eq1){throw 'Fixture forced failure after a real-index mutation.'}};$after=Get-Status $current;if((-not [string]::IsNullOrEmpty((Filter-Status $after $owned $true)))-or((Filter-Status $after $owned $false)-cne$unrelatedBefore)){throw 'Owned state was not clean or unrelated state changed after session ref advance.'}}catch{$reason=$_.Exception.Message;$rb=Invoke-Native $current 'git.exe' @('-C',$current,'update-ref',"refs/heads/$CurrentBranch",$ExpectedCurrentTip,$candidate);if($rb.ExitCode-ne 0){Stop-Candidate 1 'git.rollback-failed' "Session candidate postcondition failed and guarded ref rollback failed: $reason"};try{Restore-IndexPathSnapshot $current $indexSnapshot;$restored=Get-Status $current;if(-not(Test-IndexPathSnapshot $current $indexSnapshot)-or(Filter-Status $restored $owned $true)-cne$ownedBefore-or(Filter-Status $restored $owned $false)-cne$unrelatedBefore){Stop-Candidate 1 'git.rollback-failed' 'Session candidate rollback did not restore the owned index and disjoint state.'}}catch{Stop-Candidate 1 'git.rollback-failed' "Session candidate rollback could not restore the owned index: $($_.Exception.Message)"};Stop-Candidate 2 'candidate.postcondition-failed' $reason}}
		finally{Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue};$result.candidate.commit=$candidate;$result.candidate.tree=$tree;$result.candidate.parent=$ExpectedCurrentTip;$result.candidate.singleParent=$true;$result.candidate.reconciled=($ExpectedCurrentTip-ceq$ExpectedPrimaryTip);$result.state.after=Get-Status $current;$result.state.unrelatedPreserved=((Filter-Status $result.state.before $owned $false)-ceq(Filter-Status $result.state.after $owned $false));$result.state.realIndexUntouched=$false;Complete 0 'pass' 'candidate.created' 'Session candidate is immutable and authorized real-index entries are reconciled.'
	}
	if($current-cne$primary-or$head-cne$ExpectedPrimaryTip-or$primaryHead-cne$ExpectedPrimaryTip){Stop-Candidate 2 'git.tip-changed' 'Primary candidate route must start at the expected primary tip.'};if($declared.Count-eq 0){Stop-Candidate 1 'input.owned-paths-empty' 'At least one caller-owned path is required.'};Assert-LiteralPathEntries $primary $ExpectedPrimaryTip $declared;$before=Get-Status $primary;$result.state.before=$before;Assert-OwnedNotMixed $before $declared;$unrelatedBefore=Filter-Status $before $declared $false
	if($AdvancePrimary){$ownedBefore=Filter-Status $before $declared $true;$indexSnapshot=Get-IndexPathSnapshot $primary $declared;Assert-Candidate $primary $VerifiedCandidateCommit $VerifiedCandidateTree $ExpectedPrimaryTip;$result.candidate.commit=$VerifiedCandidateCommit;$result.candidate.tree=$VerifiedCandidateTree;$result.candidate.parent=$ExpectedPrimaryTip;$result.candidate.singleParent=$true;$result.primaryAdvance.attempted=$true;$expected=if($FixtureFailure-eq'expected-tip-mismatch'){'0000000000000000000000000000000000000000'}else{$ExpectedPrimaryTip};$cas=Invoke-Native $primary 'git.exe' @('-C',$primary,'update-ref',"refs/heads/$PrimaryBranch",$VerifiedCandidateCommit,$expected);if($cas.ExitCode-ne 0){Stop-Candidate 2 'git.compare-and-swap-failed' 'Primary branch changed before exact candidate advance.'};$result.primaryAdvance.advanced=$true;try{if($FixtureFailure-eq'postcondition'){throw 'Fixture forced postcondition failure.'};$actual=(Invoke-Git $primary @('rev-parse',"refs/heads/$PrimaryBranch")).Trim();if($actual-cne$VerifiedCandidateCommit-or(Get-Tree $primary $actual)-cne$VerifiedCandidateTree){throw 'Primary ref or tree did not equal the reviewed candidate.'};$mutations=0;foreach($path in $declared){Set-IndexPathFromTree $primary $VerifiedCandidateTree $path;$mutations++;if($FixtureFailure-eq'post-index-mutation'-and$mutations-eq1){throw 'Fixture forced failure after a real-index mutation.'}};$after=Get-Status $primary;if((-not [string]::IsNullOrEmpty((Filter-Status $after $declared $true)))-or((Filter-Status $after $declared $false)-cne$unrelatedBefore)){throw 'Owned state was not clean or unrelated primary state changed.'};$result.state.after=$after;$result.state.unrelatedPreserved=$true;$result.state.realIndexUntouched=$false;Complete 0 'pass' 'candidate.advanced' 'Primary branch advanced to the exact reviewed candidate.'}catch{$reason=$_.Exception.Message;$rb=Invoke-Native $primary 'git.exe' @('-C',$primary,'update-ref',"refs/heads/$PrimaryBranch",$ExpectedPrimaryTip,$VerifiedCandidateCommit);if($rb.ExitCode-ne 0){$result.primaryAdvance.rollback='failed';Stop-Candidate 1 'git.rollback-failed' "Candidate postcondition failed and guarded rollback failed: $reason"};try{Restore-IndexPathSnapshot $primary $indexSnapshot;$restored=Get-Status $primary;if(-not(Test-IndexPathSnapshot $primary $indexSnapshot)-or(Filter-Status $restored $declared $true)-cne$ownedBefore-or(Filter-Status $restored $declared $false)-cne$unrelatedBefore){$result.primaryAdvance.rollback='failed';Stop-Candidate 1 'git.rollback-failed' 'Candidate rollback did not restore the owned index and disjoint state.'}}catch{$result.primaryAdvance.rollback='failed';Stop-Candidate 1 'git.rollback-failed' "Candidate rollback could not restore the owned index: $($_.Exception.Message)"};$result.primaryAdvance.advanced=$false;$result.primaryAdvance.rollback='restored-expected-old';Stop-Candidate 2 'candidate.postcondition-failed' $reason}}
	$tmp=Join-Path([IO.Path]::GetTempPath())('BrokenEngineFinalizeCandidate-'+[guid]::NewGuid().ToString('N')+'.index');try{$env=@{GIT_INDEX_FILE=$tmp};Invoke-Git $primary @('read-tree',$ExpectedPrimaryTip) $env|Out-Null;Invoke-Git -Root $primary -Arguments (@('add','-A','--')+@($declared|ForEach-Object{Get-LiteralPathspec $_})) -Environment $env|Out-Null;$tree=(Invoke-Git $primary @('write-tree') $env).Trim();if($FixtureFailure-eq'tree-mismatch'){$tree=$ExpectedPrimaryTip};$candidate=(Invoke-Git $primary @('commit-tree',$tree,'-p',$ExpectedPrimaryTip,'-F',$CommitMessageFile) $env).Trim()}finally{Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue};$result.candidate.commit=$candidate;$result.candidate.tree=Get-Tree $primary $candidate;$result.candidate.parent=$ExpectedPrimaryTip;$result.candidate.singleParent=$true;$result.state.after=Get-Status $primary;$result.state.unrelatedPreserved=((Filter-Status $result.state.after $declared $false)-ceq$unrelatedBefore);$result.state.realIndexUntouched=$true;Complete 0 'pass' 'candidate.created' 'Primary candidate commit is immutable and ready for verification.'
}
catch{$exit=if($_.Exception.Data.Contains('exit')){[int]$_.Exception.Data['exit']}else{1};$code=if($_.Exception.Data.Contains('code')){[string]$_.Exception.Data['code']}else{'internal.error'};Complete $exit $(if($exit-eq 2){'blocked'}else{'error'}) $code $_.Exception.Message}
