# Scratch-only coverage for the v2 Git-native reconciliation evaluator.
[CmdletBinding()] param()
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$failures=[Collections.Generic.List[string]]::new();$root=Join-Path ([IO.Path]::GetTempPath()) "BrokenEngineSessionAuditV2\$([guid]::NewGuid().ToString('N'))";$script=Join-Path $PSScriptRoot 'Test-SessionAuditRequirement.ps1'
function Assert([bool]$ok,[string]$name){if($ok){Write-Host "pass $name"}else{$failures.Add($name);Write-Host "FAIL $name"}}
function Git([string[]]$a){$o=@(& git.exe -C $root -c user.name=fixture -c user.email=fixture@example.invalid @a 2>&1);if($LASTEXITCODE -ne 0){throw "git $($a -join ' ') failed: $($o -join '; ')"};return ($o -join "`n").Trim()}
function Run($payload,[string]$case){$o=@(& "$PSHOME\pwsh.exe" -NoProfile -File $script -InputJson ($payload|ConvertTo-Json -Depth 20 -Compress) 2>&1);$code=$LASTEXITCODE;try{$j=($o -join "`n")|ConvertFrom-Json -Depth 32}catch{Assert $false "$case emits JSON";return $null};Assert ($code -eq 0) "$case exit=0";Assert ($j.schemaVersion -ceq 'broken-engine-session-audit-decision/v2') "$case schema v2";return $j}
function RunRaw([string]$payload,[string]$case){$o=@(& "$PSHOME\pwsh.exe" -NoProfile -File $script -InputJson $payload 2>&1);$code=$LASTEXITCODE;try{$j=($o -join "`n")|ConvertFrom-Json -Depth 32}catch{Assert $false "$case emits JSON";return $null};Assert ($code -eq 0) "$case exit=0";Assert ($j.required -and (@($j.reasons) -contains 'evidence.missing-malformed-or-unproven')) "$case fails closed";return $j}
function New-AuditInput([string]$candidate,[string]$reconciled,[string]$candidateParent,[string]$reconciledParent,[string[]]$primaryPaths=@(),[string[]]$overlap=@()){return [ordered]@{schemaVersion='broken-engine-session-audit-input/v2';repositoryRoot=$root;verifiedCandidateCommit=$candidate;reconciledCommit=$reconciled;dependencyOverlapEvidence=[ordered]@{verifiedParent=$candidateParent;reconciledParent=$reconciledParent;primaryChangedPaths=$primaryPaths;directDependencyPaths=@();overlappingPaths=$overlap};conflictFree=$true;requiredDomainCoverage=$true;requiredAdversarialCoverage=$true;lateSemanticFixes=$false;manualResolution=$false;invalidatedAssumptions=$false;unseenContractSignificantRegions=$false;explicitUserRequest=$false}}
try {
	New-Item -ItemType Directory -Force $root|Out-Null;Git @('init','-b','main')|Out-Null;Git @('config','core.autocrlf','false')|Out-Null;[IO.File]::WriteAllText((Join-Path $root 'base.txt'),'base',[Text.UTF8Encoding]::new($false));Git @('add','base.txt')|Out-Null;Git @('commit','-m','base')|Out-Null;$base=Git @('rev-parse','HEAD')
	Git @('checkout','-b','candidate')|Out-Null;[IO.File]::WriteAllText((Join-Path $root 'added.txt'),'candidate',[Text.UTF8Encoding]::new($false));Git @('add','added.txt')|Out-Null;Git @('commit','-m','candidate')|Out-Null;$candidate=Git @('rev-parse','HEAD')
	Git @('checkout','main')|Out-Null;[IO.File]::WriteAllText((Join-Path $root 'primary.txt'),'primary',[Text.UTF8Encoding]::new($false));Git @('add','primary.txt')|Out-Null;Git @('commit','-m','primary')|Out-Null;$primary=Git @('rev-parse','HEAD');Git @('checkout','-b','reconciled')|Out-Null;Git @('cherry-pick',$candidate)|Out-Null;$reconciled=Git @('rev-parse','HEAD')
	$decision=Run (New-AuditInput $candidate $reconciled $base $primary @('primary.txt') @()) 'identical-git-native-delta';if($null -ne $decision){Assert (-not $decision.required) 'identical delta retains evidence';Assert $decision.deltas.identical 'identical raw delta digest'}
	# A candidate carrying a delete, rename, executable mode, and (when permitted)
	# symlink exercises the native diff format without a hand-built manifest.
	Git @('checkout','-B','rich',$base)|Out-Null;[IO.File]::WriteAllText((Join-Path $root 'old.txt'),'old',[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $root 'delete.txt'),'delete',[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $root 'mode.txt'),'mode',[Text.UTF8Encoding]::new($false));Git @('add','old.txt','delete.txt','mode.txt')|Out-Null;Git @('commit','-m','rich base')|Out-Null;$richBase=Git @('rev-parse','HEAD');Git @('mv','old.txt','renamed.txt')|Out-Null;Git @('rm','delete.txt')|Out-Null;Git @('update-index','--chmod=+x','mode.txt')|Out-Null;[IO.File]::WriteAllText((Join-Path $root 'fixture-link-target.txt'),'target',[Text.UTF8Encoding]::new($false));$linkBlob=Git @('hash-object','-w','fixture-link-target.txt');Git @('update-index','--add','--cacheinfo',"120000,$linkBlob,fixture-link")|Out-Null;Git @('update-index','--add','--cacheinfo',"160000,$richBase,fixture-gitlink")|Out-Null;Git @('commit','-m','rich candidate')|Out-Null;$richCandidate=Git @('rev-parse','HEAD');$raw=Git @('diff-tree','--no-commit-id','--raw','-r',$richCandidate);Assert ($raw -match '120000' -and $raw -match '160000') 'raw Git inventory carries symlink and gitlink modes';Git @('checkout','-B','rich-reconciled',$richBase)|Out-Null;Git @('cherry-pick',$richCandidate)|Out-Null;$richReconciled=Git @('rev-parse','HEAD');$decision=Run (New-AuditInput $richCandidate $richReconciled $richBase $richBase @() @()) 'add-delete-rename-mode-symlink-gitlink';if($null -ne $decision){Assert (-not $decision.required) 'symlink-gitlink raw delta remains identical'}
	Git @('checkout','-B','changed',$primary)|Out-Null;[IO.File]::WriteAllText((Join-Path $root 'added.txt'),'changed',[Text.UTF8Encoding]::new($false));Git @('add','added.txt')|Out-Null;Git @('commit','-m','changed')|Out-Null;$changed=Git @('rev-parse','HEAD');$decision=Run (New-AuditInput $candidate $changed $base $primary @('primary.txt') @()) 'changed-delta';if($null -ne $decision){Assert $decision.required 'changed delta requires audit';Assert (@($decision.reasons) -contains 'reconciliation.delta-changed') 'changed delta reason'}
	$overlapInput=New-AuditInput $candidate $reconciled $base $primary @('primary.txt') @('primary.txt');$overlapInput.dependencyOverlapEvidence.directDependencyPaths=@('primary.txt');$decision=Run $overlapInput 'dependency-overlap';if($null -ne $decision){Assert $decision.required 'overlap requires audit';Assert (@($decision.reasons) -contains 'dependency-overlap.detected') 'overlap reason'}
	$bad=New-AuditInput $candidate $reconciled $base $primary @('wrong.txt') @();$decision=Run $bad 'evidence-mismatch';if($null -ne $decision){Assert $decision.required 'bad evidence fail closed';Assert (@($decision.reasons) -contains 'dependency-overlap.evidence-mismatch') 'bad evidence reason'}
	foreach($case in @(@('conflictFree',$false,'reconciliation.not-conflict-free'),@('requiredDomainCoverage',$false,'coverage.domain-incomplete'),@('requiredAdversarialCoverage',$false,'coverage.adversarial-incomplete'),@('lateSemanticFixes',$true,'late-semantic-fixes.present'),@('manualResolution',$true,'manual-resolution.present'),@('invalidatedAssumptions',$true,'invalidated-assumptions.present'),@('unseenContractSignificantRegions',$true,'unseen-contract-significant-regions.present'),@('explicitUserRequest',$true,'explicit-user-request'))) { $input=New-AuditInput $candidate $reconciled $base $primary @('primary.txt') @();$input.($case[0])=$case[1];$decision=Run $input "boolean-$($case[0])";if($null -ne $decision){Assert ($decision.required -and (@($decision.reasons) -contains $case[2])) "boolean-$($case[0]) reason"} }
	$malformed=New-AuditInput $candidate $reconciled $base $primary @('primary.txt') @();$malformed.conflictFree='false';$decision=Run $malformed 'boolean-wrong-type';if($null -ne $decision){Assert ($decision.required -and (@($decision.reasons) -contains 'evidence.missing-malformed-or-unproven')) 'boolean-wrong-type fails closed'}
	RunRaw '{not-json' 'malformed-json'|Out-Null
	$missing=New-AuditInput $candidate $reconciled $base $primary @('primary.txt') @();$missing.Remove('dependencyOverlapEvidence');$decision=Run $missing 'malformed-missing-overlap-evidence';if($null -ne $decision){Assert ($decision.required -and (@($decision.reasons) -contains 'evidence.missing-malformed-or-unproven')) 'malformed-missing-overlap-evidence fails closed'}
}
finally { if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force} }
if($failures.Count){Write-Host "Session audit v2 fixtures FAILED ($($failures.Count)).";exit 1};Write-Host 'Session audit v2 fixtures passed.'
