# Read-only v2 reconciliation evaluator.  Git's parent/tree delta is the
# evidence; callers cannot supply a second manifest representation to compare.
[CmdletBinding()]
param([string] $InputJson)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$result = [ordered]@{
	schemaVersion = 'broken-engine-session-audit-decision/v2'
	required = $true; reasons = @(); message = $null; repositoryRoot = $null
	commits = [ordered]@{ verifiedCandidate = $null; reconciled = $null; verifiedParent = $null; reconciledParent = $null }
	deltas = [ordered]@{ verified = $null; reconciled = $null; identical = $false }
}
$reasons=[Collections.Generic.List[string]]::new()
function Add-Reason([string]$Reason) { if (-not $reasons.Contains($Reason)) { $reasons.Add($Reason) } }
function Complete { $result.required=$reasons.Count -ne 0; $result.reasons=$reasons.ToArray(); [Console]::Out.Write(($result|ConvertTo-Json -Depth 10 -Compress)); exit 0 }
function Invoke-Native([string]$Root,[string[]]$GitArguments) { $p=[Diagnostics.ProcessStartInfo]::new();$p.FileName='git.exe';$p.WorkingDirectory=$Root;$p.UseShellExecute=$false;$p.CreateNoWindow=$true;$p.RedirectStandardOutput=$true;$p.RedirectStandardError=$true;foreach($a in @('-C',$Root)+$GitArguments){[void]$p.ArgumentList.Add($a)};$x=[Diagnostics.Process]::new();$x.StartInfo=$p;if(-not $x.Start()){throw 'Could not start git.'};$o=$x.StandardOutput.ReadToEndAsync();$e=$x.StandardError.ReadToEndAsync();$x.WaitForExit();$r=[pscustomobject]@{ExitCode=$x.ExitCode;Stdout=$o.GetAwaiter().GetResult();Stderr=$e.GetAwaiter().GetResult()};$x.Dispose();if($r.ExitCode -ne 0){throw "git $($GitArguments -join ' ') failed: $($r.Stderr.Trim())"};return $r.Stdout }
function Required($Object,[string]$Name,[string]$Context) { if($null -eq $Object -or $null -eq $Object.PSObject.Properties[$Name]){throw "$Context is missing '$Name'."};$value=$Object.$Name;if($value -is [Collections.IEnumerable] -and $value -isnot [string]){Write-Output -NoEnumerate $value}else{return $value} }
function Required-String($Object,[string]$Name,[string]$Context) { $v=Required $Object $Name $Context;if($v -isnot [string] -or [string]::IsNullOrWhiteSpace($v)){throw "$Context.$Name must be a non-empty string."};return [string]$v }
function Required-Bool($Object,[string]$Name,[string]$Context) { $v=Required $Object $Name $Context;if($v -isnot [bool]){throw "$Context.$Name must be Boolean."};return [bool]$v }
function Commit-Parent([string]$Root,[string]$Commit,[string]$Name) { if($Commit -cnotmatch '^[0-9a-f]{40}$' -or (Invoke-Native $Root @('rev-parse','--verify',"$Commit^{commit}")).Trim() -cne $Commit){throw "$Name is not an exact commit identity."};$parents=@((Invoke-Native $Root @('show','-s','--format=%P',$Commit)).Trim().Split(' ',[StringSplitOptions]::RemoveEmptyEntries));if($parents.Count -ne 1){throw "$Name must have exactly one parent."};return $parents[0] }
function Delta([string]$Root,[string]$Parent,[string]$Commit) { return Invoke-Native $Root @('diff-tree','--no-commit-id','-r','-M','--raw','--abbrev=40','-z',$Parent,$Commit,'--') }
function Sha256([string]$Text) { $sha=[Security.Cryptography.SHA256]::Create();try{return [Convert]::ToHexString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text))).ToLowerInvariant()}finally{$sha.Dispose()} }
function Paths([string]$Root,[string]$Parent,[string]$Commit) { return @((Invoke-Native $Root @('diff-tree','--no-commit-id','-r','-M','--name-only','-z',$Parent,$Commit,'--')).Split([char]0,[StringSplitOptions]::RemoveEmptyEntries)|ForEach-Object{$_.Replace('\','/')}|Sort-Object -Unique) }
function Evidence-Paths($Value,[string]$Name) { if($null -eq $Value){return @()};if($Value -is [string] -or $Value -isnot [Collections.IEnumerable]){throw "$Name must be an array."};return @(@($Value)|ForEach-Object{if($_ -isnot [string] -or [IO.Path]::IsPathRooted($_) -or $_.Replace('\','/').StartsWith('../')){throw "$Name contains an invalid repository-relative path."};$_.Replace('\','/')}|Sort-Object -Unique) }
function Same($A,$B){return (($A -join [char]0) -ceq ($B -join [char]0))}
try {
	if([string]::IsNullOrWhiteSpace($InputJson)){throw 'InputJson is missing.'};try{$input=$InputJson|ConvertFrom-Json -Depth 100 -ErrorAction Stop}catch{throw "InputJson is malformed: $($_.Exception.Message)"}
	if((Required-String $input 'schemaVersion' 'input') -cne 'broken-engine-session-audit-input/v2'){throw 'input.schemaVersion is unsupported.'}
	$root=[IO.Path]::GetFullPath((Required-String $input 'repositoryRoot' 'input')).TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar);if(-not(Test-Path -LiteralPath $root -PathType Container)){throw 'input.repositoryRoot does not exist.'};if(([IO.Path]::GetFullPath((Invoke-Native $root @('rev-parse','--show-toplevel')).Trim()).TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar)) -cne $root){throw 'input.repositoryRoot is not the Git top-level.'};$result.repositoryRoot=$root
	$verified=Required-String $input 'verifiedCandidateCommit' 'input';$reconciled=Required-String $input 'reconciledCommit' 'input';$verifiedParent=Commit-Parent $root $verified 'verifiedCandidateCommit';$reconciledParent=Commit-Parent $root $reconciled 'reconciledCommit';$result.commits.verifiedCandidate=$verified;$result.commits.reconciled=$reconciled;$result.commits.verifiedParent=$verifiedParent;$result.commits.reconciledParent=$reconciledParent
	$before=Delta $root $verifiedParent $verified;$after=Delta $root $reconciledParent $reconciled;$result.deltas.verified=Sha256 $before;$result.deltas.reconciled=Sha256 $after;$result.deltas.identical=($before -ceq $after);if(-not$result.deltas.identical){Add-Reason 'reconciliation.delta-changed'}
	$overlap=Required $input 'dependencyOverlapEvidence' 'input';$declaredParent=Required-String $overlap 'verifiedParent' 'input.dependencyOverlapEvidence';$declaredRebasedParent=Required-String $overlap 'reconciledParent' 'input.dependencyOverlapEvidence';$direct=Evidence-Paths (Required $overlap 'directDependencyPaths' 'input.dependencyOverlapEvidence') 'input.dependencyOverlapEvidence.directDependencyPaths';$declaredChanged=Evidence-Paths (Required $overlap 'primaryChangedPaths' 'input.dependencyOverlapEvidence') 'input.dependencyOverlapEvidence.primaryChangedPaths';$declaredOverlap=Evidence-Paths (Required $overlap 'overlappingPaths' 'input.dependencyOverlapEvidence') 'input.dependencyOverlapEvidence.overlappingPaths'
	[object[]]$actualChanged=@(Paths $root $verifiedParent $reconciledParent);[object[]]$candidates=@((Paths $root $verifiedParent $verified)+$direct|Sort-Object -Unique);[object[]]$actualOverlap=@($actualChanged|Where-Object{$candidates -ccontains $_}|Sort-Object -Unique);if($declaredParent -cne $verifiedParent -or $declaredRebasedParent -cne $reconciledParent -or -not(Same $declaredChanged $actualChanged)){Add-Reason 'dependency-overlap.evidence-mismatch'};if($actualOverlap.Count -ne 0 -or -not [string]::IsNullOrEmpty(($declaredOverlap -join ''))){Add-Reason 'dependency-overlap.detected'}
	if(-not(Required-Bool $input 'conflictFree' 'input')){Add-Reason 'reconciliation.not-conflict-free'};if(-not(Required-Bool $input 'requiredDomainCoverage' 'input')){Add-Reason 'coverage.domain-incomplete'};if(-not(Required-Bool $input 'requiredAdversarialCoverage' 'input')){Add-Reason 'coverage.adversarial-incomplete'};foreach($flag in @(@('lateSemanticFixes','late-semantic-fixes.present'),@('manualResolution','manual-resolution.present'),@('invalidatedAssumptions','invalidated-assumptions.present'),@('unseenContractSignificantRegions','unseen-contract-significant-regions.present'),@('explicitUserRequest','explicit-user-request'))){if(Required-Bool $input $flag[0] 'input'){Add-Reason $flag[1]}}
}
catch{$result.message=$_.Exception.Message;Add-Reason 'evidence.missing-malformed-or-unproven'}
Complete
