#if defined(BT_ENGINE)
#pragma once
#endif

#include "../../../Engine/Data/Shaders/ShaderLayoutsBase.h"
#include "TextureCounts.h" // Auto-generated by DataPacker

#if defined(BT_ENGINE)
namespace shaders
{
#endif

CONSTEXPR int kiMaxTextureCount = 200 - 16;

#if defined(BT_ENGINE)
}
#endif
