#version 460

#include "ShaderLayouts.h"
#include "ShaderFunctions.h"

layout (local_size_x = kiParticleUpdateGroupSize) in;

layout (binding = 0) uniform globalUniform
{
    GlobalLayout globalLayout;
};

layout (scalar, binding = 1) buffer particlesUniform
{
	ParticlesLayout particles;
};

layout (binding = 2) uniform sampler2D elevationTextureSampler;
layout (binding = 3) uniform sampler2D windTextureSamplerOne;
layout (binding = 4) uniform sampler2D windTextureSamplerTwo;

void main()
{
	int i = int32_t(gl_GlobalInvocationID.x);

	// Bounds check for parallelized dispatch (workgroup size = 32)
	if (i >= particles.iLastCount)
	{
		return;
	}

#if defined(ENABLE_32_BIT_BOOL)
	if ((particles.puiAllocated[i / 32] & (1 << (i % 32))) == 0)
#else
	if (particles.pbAllocated[i] == 0)
#endif
	{
		return;
	}

	float fDeltaTime = particles.fDeltaTime;
	
	const float fGravity = particles.pParticles[i].fGravity;
	const float fVelocity = particles.pParticles[i].fVelocityDecay;
	const float fIntensityDecay = particles.pParticles[i].fIntensityDecay;
	const float fSizeDecay = particles.pParticles[i].fSizeDecay;
	const float fRotationDelta = particles.pParticles[i].fRotationDelta;
	const float fRotationDeltaDecay = particles.pParticles[i].fRotationDeltaDecay;

	// Position & collide terrain
	vec4 f4Position = particles.pParticles[i].f4Position + fDeltaTime * particles.pParticles[i].f4Velocity;
		
	vec2 f2VisibleAreaTexcoord = WorldToVisibleArea(f4Position.xyz, globalLayout.f4VisibleArea);
	float fTerrainElevation = texture(elevationTextureSampler, f2VisibleAreaTexcoord).x;
	if (f4Position.z < fTerrainElevation)
	{
		particles.pParticles[i].f4Velocity.z = abs(particles.pParticles[i].f4Velocity.z);
		particles.pParticles[i].f4Position = particles.pParticles[i].f4Position + fDeltaTime * particles.pParticles[i].f4Velocity;
	}
	else
	{
		particles.pParticles[i].f4Position = f4Position;

		// Velocity
		particles.pParticles[i].f4Velocity.z -= fDeltaTime * fGravity;
	}
		
	// Velocity decay
	particles.pParticles[i].f4Velocity *= (1.0f - fDeltaTime * fVelocity);

	// Wind force
	vec2 f2SmokeTexcoord = WorldToVisibleArea(f4Position.xyz, globalLayout.f4SmokeArea);
	vec2 f2Wind = globalLayout.fWindTextureIndex < 0.5
		? texture(windTextureSamplerOne, f2SmokeTexcoord).rg
		: texture(windTextureSamplerTwo, f2SmokeTexcoord).rg;
	particles.pParticles[i].f4Velocity.xy += fDeltaTime * globalLayout.fParticlesWindStrength * f2Wind;

	// Intensity decay
	particles.pParticles[i].fVisibleIntensity *= (1.0f - fDeltaTime * fIntensityDecay);
	particles.pParticles[i].fLightingIntensity *= (1.0f - fDeltaTime * fIntensityDecay);
		
	// Size decay
	float fSizeMultiplier = 1.0f - fDeltaTime * fSizeDecay;
	particles.pParticles[i].fSize *= fSizeMultiplier;
	particles.pParticles[i].fLength *= fSizeMultiplier;
		
	// Rotation delta
	particles.pParticles[i].fRotation += fDeltaTime * fRotationDelta;

	// Rotation delta decay
	particles.pParticles[i].fRotationDelta *= 1.0f - fDeltaTime * fRotationDeltaDecay;
		
	// If the particle hits the water or the intensity/size drops below epsilon, flag slot as free
	const float fSizeEpsilon = 0.01f;
	const float fIntensityEpsilon = 0.5f;
	if (f4Position.z < 0.0f ||
	    particles.pParticles[i].fSize < fSizeEpsilon ||
		particles.pParticles[i].fVisibleIntensity < fIntensityEpsilon)
	{
	#if defined(ENABLE_32_BIT_BOOL)
		particles.puiAllocated[i / 32] &= ~(1 << (i % 32));
	#else
		particles.pbAllocated[i] = uint8_t(0);
	#endif

		// Update the lowest free index
		atomicMin(particles.iMinFreeIndex, i);
	}
}
