#version 460

#include "ShaderLayouts.h"

layout (local_size_x = kiComputeTileSize, local_size_y = kiComputeTileSize) in;

layout (binding = 0) uniform globalUniform
{
	GlobalLayout globalLayout;
};

layout (binding = 1) uniform sampler2D spreadTexturesR[kiMaxLightingSpreadPasses];
layout (binding = 2) uniform sampler2D spreadTexturesG[kiMaxLightingSpreadPasses];
layout (binding = 3) uniform sampler2D spreadTexturesB[kiMaxLightingSpreadPasses];
layout (binding = 4, rgba16f) uniform image2D accumImageR;
layout (binding = 5, rgba16f) uniform image2D accumImageG;
layout (binding = 6, rgba16f) uniform image2D accumImageB;

layout (push_constant) uniform PushConstants
{
	uint uiSpreadIndex;
	uint uiWidth;
	uint uiHeight;
};

void main()
{
	uint uiX = gl_GlobalInvocationID.x;
	uint uiY = gl_GlobalInvocationID.y;
	if (uiX >= uiWidth || uiY >= uiHeight)
		return;

	vec2 f2Uv = (vec2(uiX, uiY) + vec2(0.5f)) / vec2(uiWidth, uiHeight);
	ivec2 i2Coord = ivec2(uiX, uiY);

	imageStore(accumImageR, i2Coord, imageLoad(accumImageR, i2Coord) + textureLod(spreadTexturesR[uiSpreadIndex], f2Uv, 0.0f));
	imageStore(accumImageG, i2Coord, imageLoad(accumImageG, i2Coord) + textureLod(spreadTexturesG[uiSpreadIndex], f2Uv, 0.0f));
	imageStore(accumImageB, i2Coord, imageLoad(accumImageB, i2Coord) + textureLod(spreadTexturesB[uiSpreadIndex], f2Uv, 0.0f));
}
