#version 460

#include "ShaderLayouts.h"

layout (local_size_x = kiComputeTileSize, local_size_y = kiComputeTileSize) in;

layout (set = 0, binding = kiGlobalBindingGlobalUniform) uniform globalUniform
{
	GlobalLayout globalLayout;
};

layout (set = 1, binding = 1, rgba16f) uniform writeonly image2D lightingImageR;
layout (set = 1, binding = 2, rgba16f) uniform writeonly image2D lightingImageG;
layout (set = 1, binding = 3, rgba16f) uniform writeonly image2D lightingImageB;

void main()
{
	ivec2 i2Texel = ivec2(gl_GlobalInvocationID.xy) + ivec2(globalLayout.iLightingDepositMinX, globalLayout.iLightingDepositMinY);
	if (any(greaterThanEqual(i2Texel, ivec2(globalLayout.iLightingDepositMaxX, globalLayout.iLightingDepositMaxY))))
		return;

	imageStore(lightingImageR, i2Texel, vec4(0.0f));
	imageStore(lightingImageG, i2Texel, vec4(0.0f));
	imageStore(lightingImageB, i2Texel, vec4(0.0f));
}
