#version 460

#include "ShaderLayouts.h"

layout (local_size_x = kiComputeTileSize, local_size_y = kiComputeTileSize) in;

layout(push_constant) uniform pushConstants
{
	PushConstantsLayout pushConstantsLayout;
};

layout (binding = 0) uniform sampler2D intermediateSampler;
layout (binding = 1, rgba8) uniform image2D blurOutputTexture;

void main()
{
	int iWidth = floatBitsToInt(pushConstantsLayout.f4Pipeline.x);
	int iHeight = floatBitsToInt(pushConstantsLayout.f4Pipeline.y);
	float fSigma = pushConstantsLayout.f4Pipeline.z;

	uint uiX = gl_GlobalInvocationID.x;
	uint uiY = gl_GlobalInvocationID.y;

	if (uiX >= iWidth || uiY >= iHeight)
		return;

	const int iRadius = 5;
	float fInvSigma = float(iRadius) / fSigma;

	vec4 f4Total = vec4(0.0f);
	float fWeightSum = 0.0f;
	for (int j = -iRadius; j <= iRadius; ++j)
	{
		float fA = float(j) / fInvSigma;
		float fWeight = exp(-0.5f * fA * fA);
		vec2 vUv = vec2(float(uiX) + 0.5f, float(int(uiY) + j) + 0.5f) / vec2(float(iWidth), float(iHeight));
		f4Total += fWeight * texture(intermediateSampler, vUv);
		fWeightSum += fWeight;
	}

	imageStore(blurOutputTexture, ivec2(uiX, uiY), f4Total / fWeightSum);
}
