#version 460

#include "ShaderLayouts.h"

layout (local_size_x = kiComputeTileSize, local_size_y = kiComputeTileSize) in;

layout(push_constant) uniform pushConstants
{
	PushConstantsLayout pushConstantsLayout;
};

layout (set = 1, binding = 0) uniform sampler2D intermediateSampler;
layout (set = 1, binding = 1, rgba8) uniform writeonly image2D blurOutputTexture; // keCombineFormat

void main()
{
	int iWidth = floatBitsToInt(pushConstantsLayout.f4Pipeline.x);
	int iHeight = floatBitsToInt(pushConstantsLayout.f4Pipeline.y);
	float fSigma = pushConstantsLayout.f4Pipeline.z;

	uint uiX = gl_GlobalInvocationID.x;
	uint uiY = gl_GlobalInvocationID.y;

	if (uiX >= iWidth || uiY >= iHeight)
		return;

	float fPacked = pushConstantsLayout.f4Pipeline.w;
	int iRadius = int(fPacked) / 2;
	float fEdgeFalloff = fract(fPacked) * 100.0;
	float fInvSigma = float(iRadius) / fSigma;

	vec4 f4Total = vec4(0.0f);
	float fWeightSum = 0.0f;
	vec2 vInvDim = 1.0f / vec2(float(iWidth), float(iHeight));
	for (int j = -iRadius; j <= iRadius; ++j)
	{
		float fA = float(j) / fInvSigma;
		float fWeight = exp(-0.5f * fA * fA);
		vec2 vUv = vec2(float(uiX) + 0.5f, float(int(uiY) + j) + 0.5f) * vInvDim;
		f4Total += fWeight * textureLod(intermediateSampler, vUv, 0.0f);
		fWeightSum += fWeight;
	}

	vec2 vEdgeUv = vec2(float(uiX) + 0.5f, float(uiY) + 0.5f) / vec2(float(iWidth), float(iHeight));
	float fEdgeDist = max(abs(vEdgeUv.x * 2.0 - 1.0), abs(vEdgeUv.y * 2.0 - 1.0));
	imageStore(blurOutputTexture, ivec2(uiX, uiY), (f4Total / fWeightSum) * pow(1.0 - fEdgeDist, fEdgeFalloff));
}
