#version 460

#include "ShaderLayouts.h"

layout (local_size_x = kiComputeTileSize, local_size_y = kiComputeTileSize) in;

layout(push_constant) uniform pushConstants
{
	PushConstantsLayout pushConstantsLayout;
};

layout (set = 1, binding = 0) uniform sampler2D sourceSampler;
layout (set = 1, binding = 1, rgba8) uniform writeonly image2D blurIntermediateTexture; // keCombineFormat

void main()
{
	int iWidth = floatBitsToInt(pushConstantsLayout.f4Pipeline.x);
	int iHeight = floatBitsToInt(pushConstantsLayout.f4Pipeline.y);
	float fSigma = pushConstantsLayout.f4Pipeline.z;

	uint uiX = gl_GlobalInvocationID.x;
	uint uiY = gl_GlobalInvocationID.y;

	if (uiX >= iWidth || uiY >= iHeight)
		return;

	int iRadius = int(pushConstantsLayout.f4Pipeline.w) / 2;
	float fInvSigma = float(iRadius) / fSigma;

	vec4 f4Total = vec4(0.0f);
	float fWeightSum = 0.0f;
	vec2 vInvDim = 1.0f / vec2(float(iWidth), float(iHeight));
	for (int i = -iRadius; i <= iRadius; ++i)
	{
		float fA = float(i) / fInvSigma;
		float fWeight = exp(-0.5f * fA * fA);
		vec2 vUv = vec2(float(int(uiX) + i) + 0.5f, float(uiY) + 0.5f) * vInvDim;
		f4Total += fWeight * textureLod(sourceSampler, vUv, 0.0f);
		fWeightSum += fWeight;
	}

	imageStore(blurIntermediateTexture, ivec2(uiX, uiY), f4Total / fWeightSum);
}
