#include "FileManager.h"

#include "Texture.h"
#include "ExportJobs/ExportAudio.h"
#include "ExportJobs/ExportFont.h"
#include "ExportJobs/ExportScene.h"
#include "ExportJobs/ExportIsland.h"
#include "ExportJobs/ExportModel.h"
#include "ExportJobs/ExportRaw.h"
#include "ExportJobs/ExportShader.h"
#include "ExportJobs/ExportTexture.h"

using enum common::ChunkFlags;

constexpr int64_t kiDataPackerVersion = 1;

static bool sbSingleThread = false;

void Quit(const char* message, const char* title);

template <typename T>
bool RunExportJobs()
{
	bool bDirty = gpFileManager->mbCleanExport;

	std::filesystem::path manifestFile = gpFileManager->mOutputDirectory;
	manifestFile /= T::kName;
	manifestFile += ".manifest";
	bDirty |= !std::filesystem::exists(manifestFile);

	std::filesystem::path packFile = gpFileManager->mOutputDirectory;
	packFile /= T::kName;
	packFile += ".pack";
	bDirty |= !std::filesystem::exists(packFile);

	std::filesystem::path headerFile = gpFileManager->mOutputDirectory;
	headerFile /= T::kName;
	headerFile += ".h";
	bDirty |= !std::filesystem::exists(headerFile);

	std::vector<std::unique_ptr<T>> exportJobs;
	for (const std::filesystem::path& rBaseDirectory : gpFileManager->mpInputDirectories)
	{
		for (const std::filesystem::directory_entry& rDirectoryEntry : std::filesystem::recursive_directory_iterator(rBaseDirectory))
		{
			std::optional<common::ChunkFlags_t> optionalChunkFlags = T::Handles(rDirectoryEntry);
			if (optionalChunkFlags.has_value())
			{
				std::unique_ptr<T>& rpExportJob = exportJobs.emplace_back(std::make_unique<T>(optionalChunkFlags.value(), rDirectoryEntry.path()));
				bDirty |= rpExportJob->CheckDirty(packFile);
			}
		}
	}

	if (!bDirty)
	{
		return true;
	}

	Log("\"{}\" is dirty, running export", T::kName);
	ScopedLogIndent scopedLogIndent;

	// Sort by relative path to ensure chunks are in same order inside the file (for more efficient Steam patching)
	std::sort(exportJobs.begin(), exportJobs.end(), [] (const std::unique_ptr<T>& rpA, const std::unique_ptr<T>& rpB) { return common::ToLower(rpA->mRelativeDirectory.string()) < common::ToLower(rpB->mRelativeDirectory.string()); });

	// Run the jobs
	for (std::unique_ptr<T>& rpExportJob : exportJobs)
	{
		rpExportJob->mFuture = std::async(std::launch::async, &T::RunExport, rpExportJob.get());
		if (sbSingleThread)
		{
			rpExportJob->mFuture.wait();
		}
	}

	// Open temporary manifest file and write header
	std::filesystem::path temporaryManifestFile = gpFileManager->mTempDirectory;
	temporaryManifestFile /= T::kName;
	temporaryManifestFile += ".manifest";
	std::fstream temporaryManifestFileStream(temporaryManifestFile, std::ios::out | std::ios::binary);

	common::DataHeader dataHeader {};
	dataHeader.iMagic = common::DataHeader::kiMagic;
	dataHeader.iVersion = common::DataHeader::kiVersion;
	dataHeader.iChunkCount = exportJobs.size();
	temporaryManifestFileStream.write(reinterpret_cast<char*>(&dataHeader), sizeof(dataHeader));
	common::AlignOutputStream(temporaryManifestFileStream);

	// Open temporary pack file
	std::filesystem::path temporaryPackFile = gpFileManager->mTempDirectory;
	temporaryPackFile /= T::kName;
	temporaryPackFile += ".pack";
	std::fstream temporaryPackFileStream(temporaryPackFile, std::ios::out | std::ios::binary);

	// Open temporary header file and write header
	std::filesystem::path temporaryHeaderFile = gpFileManager->mTempDirectory;
	temporaryHeaderFile /= T::kName;
	temporaryHeaderFile += ".h";
	std::fstream temporaryHeaderFileStream(temporaryHeaderFile, std::ios::out);
	temporaryHeaderFileStream << "#pragma once" << std::endl;
	temporaryHeaderFileStream << std::endl;
	temporaryHeaderFileStream << "// This file is automatically generated by the Data Packer" << std::endl;
	temporaryHeaderFileStream << "// To add a Crc to this file place your data file in: BrokenEngine/Engine/Data" << std::endl;
	temporaryHeaderFileStream << "// or BrokenEngine/Projects/YOUR_PROJECT/Data" << std::endl;
	temporaryHeaderFileStream << "// Then re-build and the Data Packer will run automatically as a pre-build event" << std::endl;
	temporaryHeaderFileStream << std::endl;
	temporaryHeaderFileStream << "namespace data" << std::endl;
	temporaryHeaderFileStream << "{" << std::endl;
	temporaryHeaderFileStream << std::endl;

	bool bFailed = false;
	for (std::unique_ptr<T>& rpExportJob : exportJobs)
	{
		try
		{
			std::vector<std::byte>& rData = rpExportJob->mFuture.get();

			common::ChunkLocation chunkLocation =
			{
				.crc = rpExportJob->mCrc,
				.uiOffset = static_cast<uint64_t>(temporaryPackFileStream.tellp()),
				.uiSize = rData.size(),
			};
			temporaryManifestFileStream.write(reinterpret_cast<char*>(&chunkLocation), sizeof(chunkLocation));

			temporaryPackFileStream.write(reinterpret_cast<char*>(rData.data()), rData.size());
			common::AlignOutputStream(temporaryPackFileStream);

			temporaryHeaderFileStream << "inline constexpr common::crc_t k" << common::PathToCppVariable(rpExportJob->mRelativeFile) << "Crc = " << rpExportJob->mCrc << ";" << std::endl;
		}
		catch (const std::exception& rException)
		{
			Log("Exception thrown from future: \"{}\"", rException.what());
			std::string message = std::format("Asset: {}\n\n{}", rpExportJob->mInputPath.string(), rException.what());
			Quit(message.c_str(), "Data Packer - Export Failed");
			bFailed = true;
		}
	}

	if constexpr (std::is_same_v<T, ExportTexture>)
	{
		T::AddToHeader(temporaryHeaderFileStream, exportJobs);
	}

	temporaryHeaderFileStream << std::endl;
	temporaryHeaderFileStream << "} // namespace data" << std::endl;

	temporaryManifestFileStream.close();
	temporaryPackFileStream.close();
	temporaryHeaderFileStream.close();

	if (bFailed)
	{
		Log("\n\n\nFAILED\n\n\n");

		std::filesystem::remove(temporaryManifestFile);
		std::filesystem::remove(temporaryPackFile);
		std::filesystem::remove(temporaryHeaderFile);
	}
	else
	{

		std::filesystem::rename(temporaryManifestFile, manifestFile);
		std::filesystem::rename(temporaryPackFile, packFile);

		// Only copy header if it has changed (causes game re-compilation otherwise)
		if (!common::ContentsEqual(temporaryHeaderFile, headerFile))
		{
			std::filesystem::rename(temporaryHeaderFile, headerFile);
		}
	}

	return !bFailed;
}

bool MainThread(int argc, char* argv[])
{
	common::ThreadLocal threadLocal(1024, std::nullopt, false);

	Log("\nData Packer");
	LogIndent(1);

	VERIFY_SUCCESS(XMVerifyCPUSupport());

	Texture::StaticInit();

	auto pFileManager = std::make_unique<FileManager>(std::span(argv, argc));

	bool bSuccess = true;

	// Scene and Island need to be first as they can create new textures and models
	bSuccess &= RunExportJobs<ExportScene>();
	bSuccess &= RunExportJobs<ExportIsland>();

	GenerateIrradianceCubemaps();
	GeneratePreFilteredCubemaps();

	bSuccess &= RunExportJobs<ExportAudio>();
	bSuccess &= RunExportJobs<ExportFont>();
	bSuccess &= RunExportJobs<ExportModel>();
	bSuccess &= RunExportJobs<ExportShader>();
	bSuccess &= RunExportJobs<ExportTexture>();
	bSuccess &= RunExportJobs<ExportRaw>();

	// Generate DataTypes.h file with enum and array of data types (no CRC includes)
	std::stringstream dataTypesContent;
	dataTypesContent << "#pragma once" << std::endl;
	dataTypesContent << std::endl;
	dataTypesContent << "// This file is automatically generated by the Data Packer" << std::endl;
	dataTypesContent << std::endl;
	dataTypesContent << "namespace data" << std::endl;
	dataTypesContent << "{" << std::endl;
	dataTypesContent << std::endl;
	dataTypesContent << "enum DataTypes" << std::endl;
	dataTypesContent << "{" << std::endl;
	dataTypesContent << "\tkDataTypeAudio," << std::endl;
	dataTypesContent << "\tkDataTypeFont," << std::endl;
	dataTypesContent << "\tkDataTypeScene," << std::endl;
	dataTypesContent << "\tkDataTypeIslands," << std::endl;
	dataTypesContent << "\tkDataTypeModel," << std::endl;
	dataTypesContent << "\tkDataTypeShader," << std::endl;
	dataTypesContent << "\tkDataTypeTexture," << std::endl;
	dataTypesContent << "\tkDataTypeRaw," << std::endl;
	dataTypesContent << "" << std::endl;
	dataTypesContent << "\tkDataTypeCount" << std::endl;
	dataTypesContent << "};" << std::endl;
	dataTypesContent << std::endl;
	dataTypesContent << "inline constexpr const char* kpcDataTypeNames[kDataTypeCount] =" << std::endl;
	dataTypesContent << "{" << std::endl;
	dataTypesContent << "\t\"Audio\"," << std::endl;
	dataTypesContent << "\t\"Font\"," << std::endl;
	dataTypesContent << "\t\"Scene\"," << std::endl;
	dataTypesContent << "\t\"Islands\"," << std::endl;
	dataTypesContent << "\t\"Model\"," << std::endl;
	dataTypesContent << "\t\"Shader\"," << std::endl;
	dataTypesContent << "\t\"Texture\"," << std::endl;
	dataTypesContent << "\t\"Raw\"" << std::endl;
	dataTypesContent << "};" << std::endl;
	dataTypesContent << std::endl;
	dataTypesContent << "} // namespace data" << std::endl;

	std::string dataTypesString = dataTypesContent.str();

	std::filesystem::path dataTypesPath = gpFileManager->mOutputDirectory;
	dataTypesPath /= "DataTypes.h";

	if (!common::ContentsEqual(dataTypesString, dataTypesPath))
	{
		std::fstream dataTypesStream(dataTypesPath, std::ios::out | std::ios::binary);
		dataTypesStream << dataTypesString;
		dataTypesStream.close();
		Log("Re-generated DataTypes.h");
	}

	// Generate Data.h file with DataTypes.h include and all CRC headers
	std::stringstream dataHeaderContent;
	dataHeaderContent << "#pragma once" << std::endl;
	dataHeaderContent << std::endl;
	dataHeaderContent << "// This file is automatically generated by the Data Packer" << std::endl;
	dataHeaderContent << std::endl;
	dataHeaderContent << "#include \"DataTypes.h\"" << std::endl;
	dataHeaderContent << std::endl;
	dataHeaderContent << "#include \"Audio.h\"" << std::endl;
	dataHeaderContent << "#include \"Font.h\"" << std::endl;
	dataHeaderContent << "#include \"Scene.h\"" << std::endl;
	dataHeaderContent << "#include \"Islands.h\"" << std::endl;
	dataHeaderContent << "#include \"Model.h\"" << std::endl;
	dataHeaderContent << "#include \"Shader.h\"" << std::endl;
	dataHeaderContent << "#include \"Texture.h\"" << std::endl;
	dataHeaderContent << "#include \"Raw.h\"" << std::endl;

	std::string dataHeaderString = dataHeaderContent.str();

	std::filesystem::path dataHeaderPath = gpFileManager->mOutputDirectory;
	dataHeaderPath /= "Data.h";

	if (!common::ContentsEqual(dataHeaderString, dataHeaderPath))
	{
		std::fstream dataHeaderStream(dataHeaderPath, std::ios::out | std::ios::binary);
		dataHeaderStream << dataHeaderString;
		dataHeaderStream.close();
		Log("Re-generated Data.h");
	}

	// Copy license files from ThirdParty directories to Attribution directory in output
	gpFileManager->CopyThirdPartyLicenses();

	Log("");

	return bSuccess;
}

void Quit(const char* message, const char* title)
{
	fflush(stdout);
	MessageBox(nullptr, message, title, MB_OK | MB_SYSTEMMODAL);
}

int main(int argc, char* argv[])
{
	bool bSuccess = false;

	if (IsDebuggerPresent() == TRUE)
	{
		bSuccess = MainThread(argc, argv);
	}
	else
	{
		try
		{
			bSuccess = MainThread(argc, argv);
		}
		catch (const std::exception& rException)
		{
			Quit(rException.what(), "Data Packer - std::exception");
		}
		catch (...)
		{
			Quit("", "Data Packer - Unknown exception");
		}
	}

	fflush(stdout);
	return bSuccess ? 0 : 1;
}

// CRT debug memory leak tracking
#if defined(DEBUG) || defined(_DEBUG)
	#define _CRTDBG_MAP_ALLOC
#endif

#if defined(_CRTDBG_MAP_ALLOC)
	#include <crtdbg.h>
#endif

#if defined(_CRTDBG_MAP_ALLOC)

[[nodiscard]] _Ret_notnull_ _Post_writable_byte_size_(n) void* operator new(std::size_t n) noexcept(false) { void* p = malloc(n); __assume(p); return p; }
[[nodiscard]] _Ret_notnull_ _Post_writable_byte_size_(n) void* operator new[](std::size_t n) noexcept(false) { void* p = malloc(n); __assume(p); return p; }
[[nodiscard]] _Ret_maybenull_ _Success_(return != NULL) _Post_writable_byte_size_(n) void* operator new  (std::size_t n, const std::nothrow_t&) noexcept { return malloc(n); }
[[nodiscard]] _Ret_maybenull_ _Success_(return != NULL) _Post_writable_byte_size_(n) void* operator new[](std::size_t n, const std::nothrow_t&) noexcept { return malloc(n); }
[[nodiscard]] _Ret_notnull_ _Post_writable_byte_size_(n) void* operator new  (std::size_t n, std::align_val_t al) noexcept(false) { void* p = _aligned_malloc(n, static_cast<size_t>(al)); __assume(p); return p; }
[[nodiscard]] _Ret_notnull_ _Post_writable_byte_size_(n) void* operator new[](std::size_t n, std::align_val_t al) noexcept(false) { void* p = _aligned_malloc(n, static_cast<size_t>(al)); __assume(p); return p; }
[[nodiscard]] _Ret_maybenull_ _Success_(return != NULL) _Post_writable_byte_size_(n) void* operator new  (std::size_t n, std::align_val_t al, const std::nothrow_t&) noexcept { return _aligned_malloc(n, static_cast<size_t>(al)); }
[[nodiscard]] _Ret_maybenull_ _Success_(return != NULL) _Post_writable_byte_size_(n) void* operator new[](std::size_t n, std::align_val_t al, const std::nothrow_t&) noexcept { return _aligned_malloc(n, static_cast<size_t>(al)); }

void operator delete(void* p) noexcept { free(p); }
void operator delete[](void* p) noexcept { free(p); }
void operator delete  (void* p, const std::nothrow_t&) noexcept { free(p); }
void operator delete[](void* p, const std::nothrow_t&) noexcept { free(p); }
void operator delete  (void* p, std::size_t) noexcept { free(p); }
void operator delete[](void* p, std::size_t) noexcept { free(p); }
void operator delete  (void* p, std::align_val_t) noexcept { _aligned_free(p); }
void operator delete[](void* p, std::align_val_t) noexcept { _aligned_free(p); }
void operator delete  (void* p, std::size_t, std::align_val_t) noexcept { _aligned_free(p); }
void operator delete[](void* p, std::size_t, std::align_val_t) noexcept { _aligned_free(p); }
void operator delete  (void* p, std::align_val_t, const std::nothrow_t&) noexcept { _aligned_free(p); }
void operator delete[](void* p, std::align_val_t, const std::nothrow_t&) noexcept { _aligned_free(p); }

struct CrtBreakAllocSetter
{
	CrtBreakAllocSetter()
	{
		_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);

		// Set to the allocation number from the CRT leak report to break on that allocation
		// _crtBreakAlloc = 5374;
	}
};

CrtBreakAllocSetter gCrtBreakAllocSetter;

#endif
