#include "DiagnosticReporter.h"
#include "FileManager.h"

#include "Attribution.h"
#include "ExportJobs/ExportAudio.h"
#include "ExportJobs/ExportCubemapIbl.h"
#include "ExportJobs/ExportScene.h"
#include "ExportJobs/ExportIsland.h"
#include "ExportJobs/ExportJob.h"
#include "ExportJobs/ExportModel.h"
#include "ExportJobs/ExportRaw.h"
#include "ExportJobs/ExportShader.h"
#include "ExportJobs/ExportTexture.h"
#include "ExportJobs/Island/BakeIslandIntermediates.h"
#include "ExportJobs/Texture/MigrateLegacyIntermediates.h"
#include "ExportJobs/Texture/RdoSweep.h"
#include "ExportJobs/Texture/Texture.h"

struct DataTypeEntry
{
	std::string_view enumSuffix;
	std::string_view displayName;
	std::string_view headerFile;
};

// Source of truth for the data-type enum, display names, and per-type CRC header
// includes. The order here defines the integer values of the generated DataTypes
// enum and is consumed by the runtime via `kpcDataTypeNames[kDataType...]`.
static constexpr DataTypeEntry kDataTypes[] =
{
	{"Audio",   "Audio",   "Audio.h"},
	{"Scene",   "Scene",   "Scene.h"},
	{"Islands", "Islands", "Islands.h"},
	{"Model",   "Model",   "Model.h"},
	{"Shader",  "Shader",  "Shader.h"},
	{"Texture", "Texture", "Texture.h"},
	{"Raw",     "Raw",     "Raw.h"},
};
static constexpr size_t kDataTypeCount = std::size(kDataTypes);

static void WriteIfChanged(const std::string& rContent, const std::filesystem::path& rPath, const char* logName)
{
	if (!common::ContentsEqual(rContent, rPath))
	{
		if (gpFileManager->EnsureLocal(FileManager::OutputRoot::kData) == FileManager::EnsureLocalResult::kCancelled)
		{
			throw diagnostic::AlreadyReportedError("Output materialization cancelled");
		}
		std::fstream stream(rPath, std::ios::out | std::ios::binary);
		stream << rContent;
		stream.close();
		VERIFY_SUCCESS(stream.good());
		LOG(kDefault, kDebug, "Re-generated {}", logName);
	}
}

template <IsExportJob T>
static void WriteCrcHeader(const std::filesystem::path& rOutPath, const std::vector<std::unique_ptr<T>>& rJobs)
{
	std::fstream stream(rOutPath, std::ios::out | std::ios::binary);
	stream << "#pragma once" << std::endl;
	stream << std::endl;
	stream << "// This file is automatically generated by the Data Packer" << std::endl;
	stream << "// To add a Crc to this file place your data file in: BrokenEngine/Engine/Data" << std::endl;
	stream << "// or BrokenEngine/Projects/YOUR_PROJECT/Data" << std::endl;
	stream << "// Then re-build and the Data Packer will run automatically as a pre-build event" << std::endl;
	stream << std::endl;
	stream << "namespace data" << std::endl;
	stream << "{" << std::endl;
	stream << std::endl;
	for (const std::unique_ptr<T>& rpJob : rJobs)
	{
		stream << "inline constexpr common::crc_t k" << common::PathToCppVariable(rpJob->mRelativeFile) << "Crc = " << rpJob->mCrc << "ull;" << std::endl;
	}
	stream << std::endl;
	stream << "} // namespace data" << std::endl;
	stream.close();
	VERIFY_SUCCESS(stream.good());
}

template <IsExportJob T>
bool RunExportJobs()
{
	bool bDirty = gpFileManager->mbCleanExport;

	std::filesystem::path manifestFile = gpFileManager->mOutputDirectory;
	manifestFile /= T::kName;
	manifestFile += ".manifest";
	bDirty |= !std::filesystem::exists(manifestFile);

	int64_t iManifestChunkCount = -1;
	std::vector<common::ChunkLocation> manifestChunkLocations;
	if (!bDirty)
	{
		// A lone kiVersion bump must re-export everything — the engine ASSERTs on a stale-version manifest and there is no recovery CLI
		common::DataHeader dataHeader {};
		std::fstream manifestFileStream(manifestFile, std::ios::in | std::ios::binary);
		manifestFileStream.read(reinterpret_cast<char*>(&dataHeader), sizeof(dataHeader));
		bDirty |= !manifestFileStream || dataHeader.iMagic != common::DataHeader::kiMagic || dataHeader.iVersion != common::DataHeader::kiVersion;
		iManifestChunkCount = dataHeader.iChunkCount;

		if (!bDirty)
		{
			static constexpr uint64_t kuiChunkTableOffset = static_cast<uint64_t>(common::RoundUp<int64_t, common::kiAlignmentBytes>(static_cast<int64_t>(sizeof(common::DataHeader))));
			std::error_code manifestSizeError;
			const uintmax_t uiManifestFileSizeValue = std::filesystem::file_size(manifestFile, manifestSizeError);
			if (manifestSizeError
				|| uiManifestFileSizeValue > std::numeric_limits<uint64_t>::max()
				|| uiManifestFileSizeValue > static_cast<uintmax_t>(std::numeric_limits<std::streamoff>::max()))
			{
				bDirty = true;
			}
			else
			{
				const uint64_t uiManifestFileSize = static_cast<uint64_t>(uiManifestFileSizeValue);
				if (uiManifestFileSize < kuiChunkTableOffset)
				{
					bDirty = true;
				}
				else
				{
					const uint64_t uiManifestTableBytes = uiManifestFileSize - kuiChunkTableOffset;
					const uint64_t uiMaxChunks = uiManifestTableBytes / static_cast<uint64_t>(sizeof(common::ChunkLocation));
					const bool bChunkCountInRange = dataHeader.iChunkCount >= 0
						&& static_cast<uint64_t>(dataHeader.iChunkCount) <= uiMaxChunks
						&& static_cast<uint64_t>(dataHeader.iChunkCount) <= static_cast<uint64_t>(std::numeric_limits<size_t>::max())
						&& static_cast<uint64_t>(dataHeader.iChunkCount) <= static_cast<uint64_t>(std::numeric_limits<std::streamsize>::max()) / sizeof(common::ChunkLocation);
					if (!bChunkCountInRange)
					{
						bDirty = true;
					}
					else
					{
						const uint64_t uiChunkTableBytes = static_cast<uint64_t>(dataHeader.iChunkCount) * sizeof(common::ChunkLocation);
						try
						{
							manifestChunkLocations.resize(static_cast<size_t>(dataHeader.iChunkCount));
						}
						catch (const std::exception&)
						{
							bDirty = true;
						}

						if (!bDirty)
						{
							manifestFileStream.seekg(static_cast<std::streamoff>(kuiChunkTableOffset), std::ios::beg);
							if (!manifestFileStream)
							{
								bDirty = true;
							}
							else if (uiChunkTableBytes > 0)
							{
								manifestFileStream.read(reinterpret_cast<char*>(manifestChunkLocations.data()), static_cast<std::streamsize>(uiChunkTableBytes));
								bDirty |= !manifestFileStream || manifestFileStream.gcount() != static_cast<std::streamsize>(uiChunkTableBytes);
							}
						}
					}
				}
			}
		}
	}

	std::filesystem::path packFile = gpFileManager->mOutputDirectory;
	packFile /= T::kName;
	packFile += ".pack";
	bDirty |= !std::filesystem::exists(packFile);

	std::filesystem::path headerFile = gpFileManager->mOutputDirectory;
	headerFile /= T::kName;
	headerFile += ".h";
	bDirty |= !std::filesystem::exists(headerFile);

	std::vector<std::unique_ptr<T>> exportJobs;
	for (const std::filesystem::path& rBaseDirectory : gpFileManager->mpInputDirectories)
	{
		for (const std::filesystem::directory_entry& rDirectoryEntry : std::filesystem::recursive_directory_iterator(rBaseDirectory))
		{
			std::optional<common::ChunkFlags_t> optionalChunkFlags = T::Handles(rDirectoryEntry);
			if (optionalChunkFlags.has_value())
			{
				std::unique_ptr<T>& rpExportJob = exportJobs.emplace_back(std::make_unique<T>(optionalChunkFlags.value(), rDirectoryEntry.path()));
				bDirty |= rpExportJob->CheckDirty(packFile);
			}
		}
	}

	// A deleted source asset shrinks the job list but dirties nothing above, so the stale chunk would
	// persist in .pack/.manifest (and its constant in the generated header) until an unrelated edit.
	// Comparing the manifest's chunk count against the live job count is the cheap deleted-asset
	// detector (iManifestChunkCount stays -1 when the manifest was missing/invalid, but bDirty is
	// already set in that case so the comparison is moot).
	bDirty |= iManifestChunkCount != static_cast<int64_t>(exportJobs.size());

	// Each job commits its .meta fingerprint at export time on a worker thread, but the pack/manifest
	// rename below happens later on this thread — a kill in that window leaves every fingerprint clean
	// while the published pack is stale, and nothing above compares the two. A fingerprint newer than
	// the published pack therefore dirties the aggregate; the jobs themselves stay clean, so the pack
	// is reassembled from the cached chunks without re-exporting.
	if (!bDirty)
	{
		std::error_code packError;
		std::filesystem::file_time_type packTime = std::filesystem::last_write_time(packFile, packError);
		for (const std::unique_ptr<T>& rpExportJob : exportJobs)
		{
			std::error_code metadataError;
			std::filesystem::file_time_type metadataTime = std::filesystem::last_write_time(rpExportJob->mCacheMetadataFile, metadataError);
			if (packError || metadataError || packTime < metadataTime)
			{
				LOG(kDefault, kDebug, "Pack file \"{}\" is older than fingerprint \"{}\"", packFile.string(), rpExportJob->mCacheMetadataFile.string());
				bDirty = true;
				break;
			}
		}
	}

	if (!bDirty)
	{
		std::error_code packSizeError;
		const uintmax_t uiPackFileSizeValue = std::filesystem::file_size(packFile, packSizeError);
		if (packSizeError
			|| uiPackFileSizeValue > std::numeric_limits<uint64_t>::max()
			|| uiPackFileSizeValue > static_cast<uintmax_t>(std::numeric_limits<std::streamoff>::max()))
		{
			bDirty = true;
		}
		else
		{
			const uint64_t uiPackFileSize = static_cast<uint64_t>(uiPackFileSizeValue);
			std::fstream packFileStream(packFile, std::ios::in | std::ios::binary);
			if (!packFileStream)
			{
				bDirty = true;
			}
			else
			{
				static constexpr uint64_t kuiAlignmentBytes = static_cast<uint64_t>(common::kiAlignmentBytes);
				uint64_t uiExpectedOffset = 0;
				for (const common::ChunkLocation& rChunkLocation : manifestChunkLocations)
				{
					if (rChunkLocation.uiOffset != uiExpectedOffset
						|| rChunkLocation.uiOffset % kuiAlignmentBytes != 0
						|| rChunkLocation.uiOffset > uiPackFileSize
						|| rChunkLocation.uiSize < static_cast<uint64_t>(common::kiChunkDataOffset)
						|| rChunkLocation.uiSize > uiPackFileSize - rChunkLocation.uiOffset)
					{
						bDirty = true;
						break;
					}

					common::ChunkHeader chunkHeader {};
					packFileStream.seekg(static_cast<std::streamoff>(rChunkLocation.uiOffset), std::ios::beg);
					if (!packFileStream)
					{
						bDirty = true;
						break;
					}
					packFileStream.read(reinterpret_cast<char*>(&chunkHeader), sizeof(chunkHeader));
					if (!packFileStream
						|| packFileStream.gcount() != static_cast<std::streamsize>(sizeof(chunkHeader))
						|| chunkHeader.iMagic != common::ChunkHeader::kiMagic
						|| chunkHeader.crc != rChunkLocation.crc)
					{
						bDirty = true;
						break;
					}

					const uint64_t uiChunkEnd = rChunkLocation.uiOffset + rChunkLocation.uiSize;
					const uint64_t uiPadding = (kuiAlignmentBytes - (uiChunkEnd % kuiAlignmentBytes)) % kuiAlignmentBytes;
					if (uiChunkEnd > std::numeric_limits<uint64_t>::max() - uiPadding)
					{
						bDirty = true;
						break;
					}
					uiExpectedOffset = uiChunkEnd + uiPadding;
				}

				if (!bDirty && uiExpectedOffset != uiPackFileSize)
				{
					bDirty = true;
				}
			}
		}
	}

	if (!bDirty)
	{
		return true;
	}
	if (gpFileManager->EnsureLocal(FileManager::OutputRoot::kData) == FileManager::EnsureLocalResult::kCancelled)
	{
		throw diagnostic::AlreadyReportedError("Output materialization cancelled");
	}

	LOG(kDefault, kDebug, "\"{}\" is dirty, running export", T::kName);
	ScopedLogIndent scopedLogIndent;

	// Sort by relative path to ensure chunks are in same order inside the file (for more efficient Steam patching)
	std::sort(exportJobs.begin(), exportJobs.end(), [] (const std::unique_ptr<T>& rpA, const std::unique_ptr<T>& rpB) { return common::ToLower(rpA->mRelativeFile) < common::ToLower(rpB->mRelativeFile); });

	// The two input roots (engine Data + project Data) can hold the same relative path; ExportJob
	// derives mRelativeFile/mCrc (mCrc = Crc(mRelativeFile)) from whichever root matched, so the
	// duplicates would silently produce two manifest entries with one CRC (ambiguous runtime lookup)
	// plus two identically named generated constants. Case-folded duplicates sort adjacent under the
	// comparator above, so the adjacent-pair walk catches every such collision; guaranteeing unique
	// lowered keys also makes the sort fully deterministic (no tied keys for std::sort to order
	// arbitrarily). A CRC equality check is intentionally omitted: identical paths already trip the
	// case-folded compare, and a hash collision between two DISTINCT paths is astronomically unlikely
	// and would not sort adjacent anyway — not the bug class this guards.
	for (size_t uiJob = 1; uiJob < exportJobs.size(); ++uiJob)
	{
		const T& rPrevious = *exportJobs.at(uiJob - 1);
		const T& rCurrent = *exportJobs.at(uiJob);
		if (common::ToLower(rPrevious.mRelativeFile) == common::ToLower(rCurrent.mRelativeFile))
		{
			throw std::runtime_error(std::format("\"{}\" export has a duplicate asset: \"{}\" and \"{}\" resolve to the same relative path across input roots \"{}\" and \"{}\". Rename or remove one so each chunk keeps a unique manifest key.", T::kName, rPrevious.mInputPath.string(), rCurrent.mInputPath.string(), gpFileManager->mpInputDirectories[0].string(), gpFileManager->mpInputDirectories[1].string()));
		}
	}

	// Run the jobs
	for (std::unique_ptr<T>& rpExportJob : exportJobs)
	{
		rpExportJob->mFuture = std::async(std::launch::async, &T::RunExport, rpExportJob.get());
	}

	// Open temporary manifest file and write header
	std::filesystem::path temporaryManifestFile = gpFileManager->mCacheDirectory;
	temporaryManifestFile /= T::kName;
	temporaryManifestFile += ".manifest";
	std::fstream temporaryManifestFileStream(temporaryManifestFile, std::ios::out | std::ios::binary);

	common::DataHeader dataHeader {};
	dataHeader.iMagic = common::DataHeader::kiMagic;
	dataHeader.iVersion = common::DataHeader::kiVersion;
	dataHeader.iChunkCount = exportJobs.size();
	temporaryManifestFileStream.write(reinterpret_cast<char*>(&dataHeader), sizeof(dataHeader));
	common::AlignOutputStream(temporaryManifestFileStream);

	// Open temporary pack file
	std::filesystem::path temporaryPackFile = gpFileManager->mCacheDirectory;
	temporaryPackFile /= T::kName;
	temporaryPackFile += ".pack";
	std::fstream temporaryPackFileStream(temporaryPackFile, std::ios::out | std::ios::binary);

	std::filesystem::path temporaryHeaderFile = gpFileManager->mCacheDirectory;
	temporaryHeaderFile /= T::kName;
	temporaryHeaderFile += ".h";

	std::vector<diagnostic::ExportFailure> failures;
	failures.reserve(exportJobs.size() + 1);
	for (std::unique_ptr<T>& rpExportJob : exportJobs)
	{
		try
		{
			std::vector<std::byte>& rData = rpExportJob->mFuture.get();

			common::ChunkLocation chunkLocation =
			{
				.crc = rpExportJob->mCrc,
				.uiOffset = static_cast<uint64_t>(temporaryPackFileStream.tellp()),
				.uiSize = rData.size(),
				.contentCrc = rData.empty() ? common::kCrcSeed : common::Crc(rData.data(), static_cast<int64_t>(rData.size())),
			};
			temporaryManifestFileStream.write(reinterpret_cast<char*>(&chunkLocation), sizeof(chunkLocation));

			temporaryPackFileStream.write(reinterpret_cast<char*>(rData.data()), rData.size());
			common::AlignOutputStream(temporaryPackFileStream);
		}
		catch (const std::exception& rException)
		{
			failures.push_back({.assetPath = rpExportJob->mInputPath, .message = rException.what()});
		}
	}

	temporaryManifestFileStream.close();
	temporaryPackFileStream.close();

	// Trust boundary: a disk-full / IO failure during the writes above sets badbit but leaves failures
	// empty, so without this check the success path would rename truncated manifest/pack output over the good files.
	if (!temporaryManifestFileStream.good() || !temporaryPackFileStream.good())
	{
		failures.push_back({.message = std::format("Stream write failed for \"{}\" manifest/pack output", T::kName)});
	}

	bool bFailed = !failures.empty();
	if (bFailed)
	{
		diagnostic::Record record
		{
			.eSeverity = diagnostic::Severity::kError,
			.title = "Data Packer - Export Failed",
			.message = "One or more export jobs failed",
			.eButtons = diagnostic::ButtonContract::kOk,
			.eIcon = diagnostic::ModalIcon::kNone,
			.exportFailures = std::move(failures),
		};
		diagnostic::Report(record);

		std::filesystem::remove(temporaryManifestFile);
		std::filesystem::remove(temporaryPackFile);
	}
	else
	{
		WriteCrcHeader(temporaryHeaderFile, exportJobs);

		// Only copy header if it has changed (causes game re-compilation otherwise). The header must publish
		// before the pack: the pack rename is the commit point every dirty check keys off, so a header
		// renamed after it would strand on a kill — pack/manifest new, every fingerprint older than the
		// fresh pack, and the header check above only tests existence, never staleness. Publishing first
		// cannot strand it: the constants are Crc(mRelativeFile), path-derived only, so the header changes
		// only when the asset path set changes, and every such cause re-dirties against the still-old pack
		// next run — an added/removed asset trips the manifest chunk-count comparison, a count-preserving
		// rename trips CheckDirty and the fingerprint-newer-than-pack check, and a regenerated missing
		// header already matches the pack.
		if (!common::ContentsEqual(temporaryHeaderFile, headerFile))
		{
			std::filesystem::rename(temporaryHeaderFile, headerFile);
		}
		else
		{
			std::filesystem::remove(temporaryHeaderFile);
		}

		std::filesystem::rename(temporaryManifestFile, manifestFile);
		std::filesystem::rename(temporaryPackFile, packFile);
	}

	return !bFailed;
}

template <typename... Ts>
static bool RunAllMainExports()
{
	// Comma fold (not `&& ...`) so every export runs even if an earlier one fails;
	// matches the original explicit `bSuccess &= RunExportJobs<...>()` sequence.
	bool bSuccess = true;
	((bSuccess &= RunExportJobs<Ts>()), ...);
	return bSuccess;
}

static void GenerateDataTypesHeader(const std::filesystem::path& rOutPath)
{
	std::stringstream content;
	content << "#pragma once" << std::endl;
	content << std::endl;
	content << "// This file is automatically generated by the Data Packer" << std::endl;
	content << std::endl;
	content << "namespace data" << std::endl;
	content << "{" << std::endl;
	content << std::endl;
	content << "enum DataTypes" << std::endl;
	content << "{" << std::endl;
	for (const DataTypeEntry& rEntry : kDataTypes)
	{
		content << "\tkDataType" << rEntry.enumSuffix << "," << std::endl;
	}
	content << "" << std::endl;
	content << "\tkDataTypeCount" << std::endl;
	content << "};" << std::endl;
	content << std::endl;
	content << "inline constexpr const char* kpcDataTypeNames[kDataTypeCount] =" << std::endl;
	content << "{" << std::endl;
	for (size_t i = 0; i < kDataTypeCount; ++i)
	{
		content << "\t\"" << kDataTypes[i].displayName << "\"";
		if (i + 1 < kDataTypeCount)
		{
			content << ",";
		}
		content << std::endl;
	}
	content << "};" << std::endl;
	content << std::endl;
	content << "} // namespace data" << std::endl;

	WriteIfChanged(content.str(), rOutPath, "DataTypes.h");
}

static void GenerateDataHeader(const std::filesystem::path& rOutPath)
{
	std::stringstream content;
	content << "#pragma once" << std::endl;
	content << std::endl;
	content << "// This file is automatically generated by the Data Packer" << std::endl;
	content << std::endl;
	content << "#include \"DataTypes.h\"" << std::endl;
	content << std::endl;
	for (const DataTypeEntry& rEntry : kDataTypes)
	{
		content << "#include \"" << rEntry.headerFile << "\"" << std::endl;
	}

	WriteIfChanged(content.str(), rOutPath, "Data.h");
}

bool MainThread(int argc, char* argv[])
{
	common::ThreadLocal threadLocal(1024, std::nullopt, false);

	LOG(kDefault, kDebug, "\nData Packer");
	ScopedLogIndent scopedLogIndent;

	VERIFY_SUCCESS(XMVerifyCPUSupport());

	Texture::StaticInit();

	auto pFileManager = std::make_unique<FileManager>(std::span(argv, argc));

	MigrateLegacyIntermediates();

	bool bSuccess = true;

	// Scene and Island need to be first as they can create new textures and models
	bSuccess &= RunExportJobs<ExportScene>();
	BakeIslandIntermediates();
	bSuccess &= RunExportJobs<ExportIsland>();

	GenerateIrradianceCubemaps();
	GeneratePreFilteredCubemaps();

	bSuccess &= RunAllMainExports<ExportAudio, ExportModel, ExportShader, ExportTexture, ExportRaw>();

	GenerateDataTypesHeader(gpFileManager->mOutputDirectory / "DataTypes.h");
	GenerateDataHeader(gpFileManager->mOutputDirectory / "Data.h");

	// Copy license files from ThirdParty directories to Attribution directory in output
	attribution::CopyThirdPartyLicenses();

	LOG(kDefault, kDebug, "");

	return bSuccess;
}

bool MaterializeData(char* argv[])
{
	common::ThreadLocal threadLocal(1024, std::nullopt, false);
	std::array<char*, 4> fileManagerArguments { argv[0], argv[2], argv[3], argv[4] };
	auto pFileManager = std::make_unique<FileManager>(fileManagerArguments, FileManager::InitializationMode::kDataOnly);
	return gpFileManager->EnsureLocal(FileManager::OutputRoot::kData) != FileManager::EnsureLocalResult::kCancelled;
}

int main(int argc, char* argv[])
{
	// Prevent multiple instances from running simultaneously
	HANDLE hMutex = CreateMutex(nullptr, TRUE, "BrokenEngineDataPacker");
	__assume(hMutex != nullptr);
	auto mutexDeleter = [](void* pH) { ReleaseMutex(pH); CloseHandle(pH); };
	std::unique_ptr<void, decltype(mutexDeleter)> pMutex(hMutex, mutexDeleter);
	if (GetLastError() == ERROR_ALREADY_EXISTS)
	{
		std::printf("DataPacker is already running, waiting...\n");
		WaitForSingleObject(hMutex, INFINITE);
	}

	auto runOnce = [&]() -> bool
	{
		if (argc >= 2 && std::string_view(argv[1]) == "--materialize-data")
		{
			// CLI trust boundary: data materialization takes exactly the two input roots and output Data path
			if (argc != 5)
			{
				std::printf("--materialize-data requires exactly <engine-data> <project-data> <output-data>\n");
				return false;
			}
			return MaterializeData(argv);
		}
		if (argc >= 2 && std::string_view(argv[1]).starts_with("--rdo-sweep"))
		{
			// CLI trust boundary: each sweep mode takes exactly one image/intermediate path
			if (argc != 3)
			{
				std::printf("%s requires exactly one <image path> argument\n", argv[1]);
				return false;
			}
			common::ThreadLocal threadLocal(1024, std::nullopt, false);
			Texture::StaticInit();
			if (std::string_view(argv[1]) == "--rdo-sweep")
			{
				return RunRdoSweep(argv[2]) == 0;
			}
			if (std::string_view(argv[1]) == "--rdo-sweep-full")
			{
				return RunRdoSweepFull(argv[2]) == 0;
			}
			if (std::string_view(argv[1]) == "--rdo-sweep-validate")
			{
				return RunRdoSweepValidate(argv[2]) == 0;
			}
			std::printf("Unknown mode %s\n", argv[1]);
			return false;
		}
		return MainThread(argc, argv);
	};

	bool bSuccess = false;

	if (IsDebuggerPresent() == TRUE)
	{
		bSuccess = runOnce();
	}
	else
	{
		try
		{
			bSuccess = runOnce();
		}
		catch (const diagnostic::AlreadyReportedError&)
		{
		}
		catch (const std::exception& rException)
		{
			const std::string message = rException.what()[0] == '\0' ? "Empty std::exception message escaped DataPacker" : rException.what();
			diagnostic::Record record
			{
				.eSeverity = diagnostic::Severity::kError,
				.title = "Data Packer - std::exception",
				.message = message,
				.eButtons = diagnostic::ButtonContract::kOk,
				.eIcon = diagnostic::ModalIcon::kNone,
			};
			diagnostic::Report(record);
		}
		catch (...)
		{
			diagnostic::Record record
			{
				.eSeverity = diagnostic::Severity::kError,
				.title = "Data Packer - Unknown exception",
				.message = "Unknown non-standard exception escaped DataPacker",
				.eButtons = diagnostic::ButtonContract::kOk,
				.eIcon = diagnostic::ModalIcon::kNone,
			};
			diagnostic::Report(record);
		}
	}

	fflush(stdout);
	return bSuccess ? 0 : 1;
}

#if defined(_CRTDBG_MAP_ALLOC)

[[nodiscard]] _Ret_notnull_ _Post_writable_byte_size_(n) void* operator new(std::size_t n) noexcept(false) { void* p = std::malloc(n); __assume(p != nullptr); return p; }
[[nodiscard]] _Ret_notnull_ _Post_writable_byte_size_(n) void* operator new[](std::size_t n) noexcept(false) { void* p = std::malloc(n); __assume(p != nullptr); return p; }
[[nodiscard]] _Ret_maybenull_ _Success_(return != NULL) _Post_writable_byte_size_(n) void* operator new  (std::size_t n, const std::nothrow_t&) noexcept { return std::malloc(n); }
[[nodiscard]] _Ret_maybenull_ _Success_(return != NULL) _Post_writable_byte_size_(n) void* operator new[](std::size_t n, const std::nothrow_t&) noexcept { return std::malloc(n); }
[[nodiscard]] _Ret_notnull_ _Post_writable_byte_size_(n) void* operator new  (std::size_t n, std::align_val_t al) noexcept(false) { void* p = _aligned_malloc(n, static_cast<size_t>(al)); __assume(p != nullptr); return p; }
[[nodiscard]] _Ret_notnull_ _Post_writable_byte_size_(n) void* operator new[](std::size_t n, std::align_val_t al) noexcept(false) { void* p = _aligned_malloc(n, static_cast<size_t>(al)); __assume(p != nullptr); return p; }
[[nodiscard]] _Ret_maybenull_ _Success_(return != NULL) _Post_writable_byte_size_(n) void* operator new  (std::size_t n, std::align_val_t al, const std::nothrow_t&) noexcept { return _aligned_malloc(n, static_cast<size_t>(al)); }
[[nodiscard]] _Ret_maybenull_ _Success_(return != NULL) _Post_writable_byte_size_(n) void* operator new[](std::size_t n, std::align_val_t al, const std::nothrow_t&) noexcept { return _aligned_malloc(n, static_cast<size_t>(al)); }

void operator delete(void* p) noexcept { std::free(p); }
void operator delete[](void* p) noexcept { std::free(p); }
void operator delete  (void* p, const std::nothrow_t&) noexcept { std::free(p); }
void operator delete[](void* p, const std::nothrow_t&) noexcept { std::free(p); }
void operator delete  (void* p, std::size_t) noexcept { std::free(p); }
void operator delete[](void* p, std::size_t) noexcept { std::free(p); }
void operator delete  (void* p, std::align_val_t) noexcept { _aligned_free(p); }
void operator delete[](void* p, std::align_val_t) noexcept { _aligned_free(p); }
void operator delete  (void* p, std::size_t, std::align_val_t) noexcept { _aligned_free(p); }
void operator delete[](void* p, std::size_t, std::align_val_t) noexcept { _aligned_free(p); }
void operator delete  (void* p, std::align_val_t, const std::nothrow_t&) noexcept { _aligned_free(p); }
void operator delete[](void* p, std::align_val_t, const std::nothrow_t&) noexcept { _aligned_free(p); }

struct CrtBreakAllocSetter
{
	CrtBreakAllocSetter()
	{
		_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);

		// Set to the allocation number from the CRT leak report to break on that allocation
		// _crtBreakAlloc = 5374;
	}
};

CrtBreakAllocSetter gCrtBreakAllocSetter;

#endif
