#include "FileManager.h"

#include "Texture.h"
#include "ExportJobs/ExportAudio.h"
#include "ExportJobs/ExportFont.h"
#include "ExportJobs/ExportGltf.h"
#include "ExportJobs/ExportIsland.h"
#include "ExportJobs/ExportModel.h"
#include "ExportJobs/ExportRaw.h"
#include "ExportJobs/ExportShader.h"
#include "ExportJobs/ExportTexture.h"

using enum common::ChunkFlags;

constexpr int64_t kiDataPackerVersion = 1;

static bool sbSingleThread = false;

template <typename T>
bool RunExportJobs()
{
	bool bDirty = gpFileManager->mbCleanExport;

	std::filesystem::path manifestFile = gpFileManager->mOutputDirectory;
	manifestFile /= T::kName;
	manifestFile += ".manifest";
	bDirty |= !std::filesystem::exists(manifestFile);

	std::filesystem::path packFile = gpFileManager->mOutputDirectory;
	packFile /= T::kName;
	packFile += ".pack";
	bDirty |= !std::filesystem::exists(packFile);

	std::filesystem::path headerFile = gpFileManager->mOutputDirectory;
	headerFile /= T::kName;
	headerFile += ".h";
	bDirty |= !std::filesystem::exists(headerFile);

	std::vector<std::unique_ptr<T>> exportJobs;
	for (const std::filesystem::path& rBaseDirectory : gpFileManager->mpInputDirectories)
	{
		for (const std::filesystem::directory_entry& rDirectoryEntry : std::filesystem::recursive_directory_iterator(rBaseDirectory))
		{
			std::optional<common::ChunkFlags_t> optionalChunkFlags = T::Handles(rDirectoryEntry);
			if (optionalChunkFlags.has_value())
			{
				std::unique_ptr<T>& rpExportJob = exportJobs.emplace_back(std::make_unique<T>(optionalChunkFlags.value(), rDirectoryEntry.path()));
				bDirty |= rpExportJob->CheckDirty(packFile);
			}
		}
	}

	if (!bDirty)
	{
		return true;
	}

	Log("\"{}\" is dirty, running export", T::kName);
	ScopedLogIndent scopedLogIndent;

	// Sort by relative path to ensure chunks are in same order inside the file (for more efficient Steam patching)
	std::sort(exportJobs.begin(), exportJobs.end(), [] (const std::unique_ptr<T>& rpA, const std::unique_ptr<T>& rpB) { return common::ToLower(rpA->mRelativeDirectory.string()) < common::ToLower(rpB->mRelativeDirectory.string()); });

	// Run the jobs
	for (std::unique_ptr<T>& rpExportJob : exportJobs)
	{
		rpExportJob->mFuture = std::async(std::launch::async, &T::RunExport, rpExportJob.get());
		if (sbSingleThread)
		{
			rpExportJob->mFuture.wait();
		}
	}

	// Remove existing output data files (keep header so that it doesn't get copied if no changes)
	std::filesystem::remove(manifestFile);
	std::filesystem::remove(packFile);

	// Open temporary manifest file and write header
	std::filesystem::path temporaryManifestFile = gpFileManager->mTempDirectory;
	temporaryManifestFile /= T::kName;
	temporaryManifestFile += ".manifest";
	std::fstream temporaryManifestFileStream(temporaryManifestFile, std::ios::out | std::ios::binary);

	common::DataHeader dataHeader {};
	dataHeader.iMagic = common::DataHeader::kiMagic;
	dataHeader.iVersion = common::DataHeader::kiVersion;
	dataHeader.iChunkCount = exportJobs.size();
	temporaryManifestFileStream.write(reinterpret_cast<char*>(&dataHeader), sizeof(dataHeader));
	common::AlignOutputStream(temporaryManifestFileStream);

	// Open temporary pack file
	std::filesystem::path temporaryPackFile = gpFileManager->mTempDirectory;
	temporaryPackFile /= T::kName;
	temporaryPackFile += ".pack";
	std::fstream temporaryPackFileStream(temporaryPackFile, std::ios::out | std::ios::binary);

	// Open temporary header file and write header
	std::filesystem::path temporaryHeaderFile = gpFileManager->mTempDirectory;
	temporaryHeaderFile /= T::kName;
	temporaryHeaderFile += ".h";
	std::fstream temporaryHeaderFileStream(temporaryHeaderFile, std::ios::out);
	temporaryHeaderFileStream << "#pragma once" << std::endl;
	temporaryHeaderFileStream << std::endl;
	temporaryHeaderFileStream << "// This file is automatically generated by the Data Packer" << std::endl;
	temporaryHeaderFileStream << "// To add a Crc to this file place your data file in: BrokenEngine/Engine/Data" << std::endl;
	temporaryHeaderFileStream << "// or BrokenEngine/Projects/YOUR_PROJECT/Data" << std::endl;
	temporaryHeaderFileStream << "// Then re-build and the Data Packer will run automatically as a pre-build event" << std::endl;
	temporaryHeaderFileStream << std::endl;
	temporaryHeaderFileStream << "namespace data" << std::endl;
	temporaryHeaderFileStream << "{" << std::endl;
	temporaryHeaderFileStream << std::endl;

	bool bFailed = false;
	for (std::unique_ptr<T>& rpExportJob : exportJobs)
	{
		try
		{
			std::vector<byte>& rData = rpExportJob->mFuture.get();

			common::ChunkLocation chunkLocation =
			{
				.crc = rpExportJob->mCrc,
				.uiOffset = static_cast<uint64_t>(temporaryPackFileStream.tellp()),
				.uiSize = rData.size(),
			};
			temporaryManifestFileStream.write(reinterpret_cast<char*>(&chunkLocation), sizeof(chunkLocation));

			temporaryPackFileStream.write(reinterpret_cast<char*>(rData.data()), rData.size());
			common::AlignOutputStream(temporaryPackFileStream);

			temporaryHeaderFileStream << "inline constexpr common::crc_t k" << common::PathToCppVariable(rpExportJob->mRelativeFile) << "Crc = " << rpExportJob->mCrc << ";" << std::endl;
		}
		catch (const std::exception& rException)
		{
			Log("Exception thrown from future: \"{}\"", rException.what());
			bFailed = true;
		}
	}

	if constexpr (std::is_same_v<T, ExportTexture>)
	{
		T::AddToHeader(temporaryHeaderFileStream, exportJobs);
	}

	temporaryHeaderFileStream << std::endl;
	temporaryHeaderFileStream << "} // namespace data" << std::endl;

	temporaryManifestFileStream.close();
	temporaryPackFileStream.close();
	temporaryHeaderFileStream.close();

	if (bFailed)
	{
		Log("\n\n\nFAILED\n\n\n");

		std::filesystem::remove(temporaryManifestFile);
		std::filesystem::remove(temporaryPackFile);
		std::filesystem::remove(temporaryHeaderFile);
	}
	else
	{

		std::filesystem::rename(temporaryManifestFile, manifestFile);
		std::filesystem::rename(temporaryPackFile, packFile);

		// Only copy header if it has changed (causes game re-compilation otherwise)
		if (!common::ContentsEqual(temporaryHeaderFile, headerFile))
		{
			std::filesystem::rename(temporaryHeaderFile, headerFile);
		}
	}

	return !bFailed;
}

void CountTextures()
{
	int64_t iTextureCount = 0;
	int64_t iUiTextureCount = 0;

	// Extension set matching ExportTexture::Handles()
	std::unordered_set<std::string> extensionSet = {".png", ".tga", ".jpg", ".ktx", ".BC4_UNORM_BLOCK", ".BC7_UNORM_BLOCK", ".R8_UNORM", ".R8G8B8A8_UNORM", ".R16_UNORM", ".R16G16_UNORM", ".R32_SFLOAT"};

	for (const std::filesystem::path& rBaseDirectory : gpFileManager->mpInputDirectories)
	{
		for (const std::filesystem::directory_entry& rDirectoryEntry : std::filesystem::recursive_directory_iterator(rBaseDirectory))
		{
			// Skip cubemaps (files with [C] in name)
			if (rDirectoryEntry.path().filename().native().find(L"[C]") != std::wstring::npos)
			{
				continue;
			}

			// Check if this is a texture file
			if (!extensionSet.contains(rDirectoryEntry.path().extension().string()))
			{
				continue;
			}

			// Skip Gltf folder textures (they're embedded in glTF models)
			if (rDirectoryEntry.path().native().find(L"Gltf") != std::wstring::npos)
			{
				continue;
			}

			// Count UI textures separately
			if (rDirectoryEntry.path().native().find(L"Textures\\Ui") != std::wstring::npos)
			{
				++iUiTextureCount;
			}
			else
			{
				++iTextureCount;
			}
		}
	}

	// Generate TextureCounts.h content
	std::stringstream content;
	content << "// Auto-generated by DataPacker - DO NOT EDIT" << std::endl;
	content << "#if defined(BT_ENGINE)" << std::endl;
	content << "#pragma once" << std::endl;
	content << "#endif" << std::endl;
	content << std::endl;
	content << "CONSTEXPR int kiTextureCount = " << iTextureCount << ";" << std::endl;
	content << "CONSTEXPR int kiUiTextureCount = " << iUiTextureCount << ";" << std::endl;

	std::string contentString = content.str();

	// Write to project Shaders directory
	std::filesystem::path textureCountsPath(gpFileManager->mpInputDirectories[1]);
	textureCountsPath /= "Shaders/TextureCounts.h";

	// Only write if content changed
	if (!common::ContentsEqual(contentString, textureCountsPath))
	{
		std::fstream fileStream(textureCountsPath, std::ios::out | std::ios::binary);
		fileStream << contentString;
		fileStream.close();
		Log("Generated TextureCounts.h (textures: {}, ui: {})", iTextureCount, iUiTextureCount);
	}
}

bool MainThread(int argc, char* argv[])
{
	common::ThreadLocal threadLocal(1024);

	Log("\nData Packer");
	LogIndent(1);

	VerifySuccess(XMVerifyCPUSupport());

	Texture::StaticInit();

	auto pFileManager = std::make_unique<FileManager>(std::span(argv, argc));

	bool bSuccess = true;

	// Gltf and Island need to be first as they can create new textures and models
	bSuccess &= RunExportJobs<ExportGltf>();
	bSuccess &= RunExportJobs<ExportIsland>();

	// Generate TextureCounts.h before shader compilation
	CountTextures();

	bSuccess &= RunExportJobs<ExportAudio>();
	bSuccess &= RunExportJobs<ExportFont>();
	bSuccess &= RunExportJobs<ExportModel>();
	bSuccess &= RunExportJobs<ExportShader>();
	bSuccess &= RunExportJobs<ExportTexture>();
	bSuccess &= RunExportJobs<ExportRaw>();

	// Generate Data.h file with enum and array of data types, and generated headers
	// Build content in memory first to compare before writing to disk
	std::stringstream dataHeaderContent;
	dataHeaderContent << "#pragma once" << std::endl;
	dataHeaderContent << std::endl;
	dataHeaderContent << "// This file is automatically generated by the Data Packer" << std::endl;
	dataHeaderContent << std::endl;
	dataHeaderContent << "#include \"Audio.h\"" << std::endl;
	dataHeaderContent << "#include \"Font.h\"" << std::endl;
	dataHeaderContent << "#include \"Gltf.h\"" << std::endl;
	dataHeaderContent << "#include \"Islands.h\"" << std::endl;
	dataHeaderContent << "#include \"Model.h\"" << std::endl;
	dataHeaderContent << "#include \"Shader.h\"" << std::endl;
	dataHeaderContent << "#include \"Texture.h\"" << std::endl;
	dataHeaderContent << "#include \"Raw.h\"" << std::endl;
	dataHeaderContent << std::endl;
	dataHeaderContent << "namespace data" << std::endl;
	dataHeaderContent << "{" << std::endl;
	dataHeaderContent << std::endl;
	dataHeaderContent << "enum DataTypes" << std::endl;
	dataHeaderContent << "{" << std::endl;
	dataHeaderContent << "\tkDataTypeAudio," << std::endl;
	dataHeaderContent << "\tkDataTypeFont," << std::endl;
	dataHeaderContent << "\tkDataTypeGltf," << std::endl;
	dataHeaderContent << "\tkDataTypeIslands," << std::endl;
	dataHeaderContent << "\tkDataTypeModel," << std::endl;
	dataHeaderContent << "\tkDataTypeShader," << std::endl;
	dataHeaderContent << "\tkDataTypeTexture," << std::endl;
	dataHeaderContent << "\tkDataTypeRaw," << std::endl;
	dataHeaderContent << "" << std::endl;
	dataHeaderContent << "\tkDataTypeCount" << std::endl;
	dataHeaderContent << "};" << std::endl;
	dataHeaderContent << std::endl;
	dataHeaderContent << "inline constexpr const char* kpcDataTypeNames[kDataTypeCount] =" << std::endl;
	dataHeaderContent << "{" << std::endl;
	dataHeaderContent << "\t\"Audio\"," << std::endl;
	dataHeaderContent << "\t\"Font\"," << std::endl;
	dataHeaderContent << "\t\"Gltf\"," << std::endl;
	dataHeaderContent << "\t\"Islands\"," << std::endl;
	dataHeaderContent << "\t\"Model\"," << std::endl;
	dataHeaderContent << "\t\"Shader\"," << std::endl;
	dataHeaderContent << "\t\"Texture\"," << std::endl;
	dataHeaderContent << "\t\"Raw\"" << std::endl;
	dataHeaderContent << "};" << std::endl;
	dataHeaderContent << std::endl;
	dataHeaderContent << "} // namespace data" << std::endl;
	
	// Get the content as string
	std::string dataHeaderString = dataHeaderContent.str();
	
	// Only write Data.h if it has changed to avoid game recompilation
	std::filesystem::path dataHeaderPath = gpFileManager->mOutputDirectory;
	dataHeaderPath /= "Data.h";
	
	if (!common::ContentsEqual(dataHeaderString, dataHeaderPath))
	{
		// Write the new content to disk
		std::fstream dataHeaderStream(dataHeaderPath, std::ios::out | std::ios::binary);
		dataHeaderStream << dataHeaderString;
		dataHeaderStream.close();
		Log("Re-generated Data.h");
	}

	// Copy license files from ThirdParty directories to Attribution directory in output
	gpFileManager->CopyThirdPartyLicenses();

	Log("");

	return bSuccess;
}

void Quit(std::string_view message, std::string_view title)
{
	fflush(stdout);
	MessageBox(nullptr, message.data(), title.data(), MB_OK | MB_SYSTEMMODAL);
}

int main(int argc, char* argv[])
{
#if defined(_CRTDBG_MAP_ALLOC)
	_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
#endif

	bool bSuccess = false;

	if (IsDebuggerPresent() == TRUE)
	{
		bSuccess = MainThread(argc, argv);
	}
	else
	{
		try
		{
			bSuccess = MainThread(argc, argv);
		}
		catch (const std::exception& rException)
		{
			Quit(rException.what(), "Data Packer - std::exception");
		}
		catch (...)
		{
			Quit("", "Data Packer - Unknown exception");
		}
	}

	fflush(stdout);
	return bSuccess ? 0 : 1;
}

#if defined(_CRTDBG_MAP_ALLOC)

#pragma warning(disable:4074)
#pragma init_seg(compiler)

struct CrtBreakAllocSetter
{
	CrtBreakAllocSetter()
	{
		// _crtBreakAlloc = 5374;
		// sbSingleThread = true;
	}
};

CrtBreakAllocSetter gCrtBreakAllocSetter; 

_Ret_notnull_ _Post_writable_byte_size_(_Size) _VCRT_ALLOCATOR void* __CRTDECL operator new(size_t _Size)
{
	return malloc(_Size);
}

void __CRTDECL operator delete(void* _Block) noexcept
{
	return free(_Block);
}

_Ret_notnull_ _Post_writable_byte_size_(_Size) _VCRT_ALLOCATOR void* __CRTDECL operator new[](size_t _Size)
{
	return malloc(_Size);
}

void __CRTDECL operator delete[](void* _Block) noexcept
{
	return free(_Block);
}

#endif
