#version 460

#include "ShaderLayouts.h"

layout (local_size_x = kiComputeTileSize, local_size_y = kiComputeTileSize) in;

// Uniforms
layout (set = 0, binding = kiGlobalBindingGlobalUniform) uniform globalUniform
{
    GlobalLayout globalLayout;
};

layout (set = 1, binding = 1) uniform sampler2D objectShadowsBlurIntermediateSampler;
layout (set = 1, binding = 2, r16) uniform writeonly image2D objectShadowsBlurTexture;

void main()
{
	uint uiX = gl_GlobalInvocationID.x;
	uint uiY = gl_GlobalInvocationID.y;

	ivec2 i2Size = imageSize(objectShadowsBlurTexture);
	if (uiX >= i2Size.x || uiY >= i2Size.y)
		return;

	int iRadius = globalLayout.iObjectShadowsBlurRadius;
	float fRadiusOverSigma = float(iRadius) / max(globalLayout.fObjectShadowsBlurSigma, 1e-6f);

	vec2 f2InvSize = 1.0f / vec2(i2Size);
	vec2 f2Uv = (vec2(uiX, uiY) + 0.5f) * f2InvSize;

	float fTotal = 0.0f;
	float fWeightSum = 0.0f;
	for (int j = -iRadius; j <= iRadius; ++j)
	{
		float fA = float(j) / fRadiusOverSigma;
		float fWeight = exp(-0.5f * fA * fA);
		vec2 f2Offset = vec2(0.0f, float(j)) * f2InvSize;
		fTotal += fWeight * textureLod(objectShadowsBlurIntermediateSampler, f2Uv + f2Offset, 0.0f).x;
		fWeightSum += fWeight;
	}

	float fOutColor = 1.0f - globalLayout.fObjectShadowsIntensity * fTotal / fWeightSum;
	imageStore(objectShadowsBlurTexture, ivec2(uiX, uiY), vec4(fOutColor, 0.0f, 0.0f, 0.0f));
}
