#version 460

#include "ShaderLayouts.h"

layout (local_size_x = 8, local_size_y = 8) in;

// Uniforms
layout (binding = 0) uniform globalUniform
{
    GlobalLayout globalLayout;
};

layout (binding = 1) uniform sampler2D objectShadowsTextureSampler;
layout (binding = 2, r16) uniform image2D objectShadowsBlurIntermediateTexture;

void main()
{
	uint uiX = gl_GlobalInvocationID.x;
	uint uiY = gl_GlobalInvocationID.y;

	ivec2 i2Size = imageSize(objectShadowsBlurIntermediateTexture);
	if (uiX >= i2Size.x || uiY >= i2Size.y)
		return;

	const int iRadius = 5;
	float fInvSigma = float(iRadius) / globalLayout.fObjectShadowsBlurSigma;

	vec2 f2Uv = (vec2(uiX, uiY) + vec2(0.5f)) / vec2(i2Size);

	float fTotal = 0.0f;
	float fWeightSum = 0.0f;
	for (int i = -iRadius; i <= iRadius; ++i)
	{
		float fA = float(i) / fInvSigma;
		float fWeight = exp(-0.5f * fA * fA);
		vec2 f2Offset = vec2(float(i), 0.0f) / vec2(i2Size);
		fTotal += fWeight * (1.0f - texture(objectShadowsTextureSampler, f2Uv + f2Offset).x);
		fWeightSum += fWeight;
	}

	imageStore(objectShadowsBlurIntermediateTexture, ivec2(uiX, uiY), vec4(fTotal / fWeightSum, 0.0f, 0.0f, 0.0f));
}
