#version 460

#include "ShaderLayouts.h"

layout (local_size_x = kiComputeTileSize, local_size_y = kiComputeTileSize) in;

// Uniforms
layout (set = 0, binding = kiGlobalBindingGlobalUniform) uniform globalUniform
{
    GlobalLayout globalLayout;
};

layout (set = 1, binding = 1) uniform sampler2D objectShadowsTextureSampler;
layout (set = 1, binding = 2, r16) uniform writeonly image2D objectShadowsBlurIntermediateTexture; // keShadowFormat

void main()
{
	uint uiX = gl_GlobalInvocationID.x;
	uint uiY = gl_GlobalInvocationID.y;

	ivec2 i2Size = imageSize(objectShadowsBlurIntermediateTexture);
	if (uiX >= i2Size.x || uiY >= i2Size.y)
		return;

	int iRadius = globalLayout.iObjectShadowsBlurRadius;
	float fRadiusOverSigma = float(iRadius) / max(globalLayout.fObjectShadowsBlurSigma, 1e-6f);

	vec2 f2InvSize = 1.0f / vec2(i2Size);
	vec2 f2Uv = (vec2(uiX, uiY) + 0.5f) * f2InvSize;

	float fTotal = 0.0f;
	float fWeightSum = 0.0f;
	for (int i = -iRadius; i <= iRadius; ++i)
	{
		float fA = float(i) / fRadiusOverSigma;
		float fWeight = exp(-0.5f * fA * fA);
		vec2 f2Offset = vec2(float(i), 0.0f) * f2InvSize;
		fTotal += fWeight * (1.0f - textureLod(objectShadowsTextureSampler, f2Uv + f2Offset, 0.0f).x);
		fWeightSum += fWeight;
	}

	imageStore(objectShadowsBlurIntermediateTexture, ivec2(uiX, uiY), vec4(fTotal / fWeightSum, 0.0f, 0.0f, 0.0f));
}
